const page=location.pathname.includes('triage')?'triage':location.pathname.includes('evidence')?'evidence':'monitor';
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const members=['Unassigned','Maya Chen','Jordan Ellis','Alex Rivera','Sam Patel'];
const cases=[
{id:'IR-2041',title:'Unusual outbound transfer',severity:'Critical',source:'Network sensor',host:'FIN-WS-014',person:'Avery Morgan',ip:'10.24.3.14',time:'09:24:18',summary:'A finance workstation transferred 48.2 MB to an unfamiliar external destination, 198.51.100.24. Review the preceding sign-in and file activity.'},
{id:'IR-2042',title:'Repeated sign-in failures',severity:'High',source:'Identity provider',host:'AUTH-SRV-02',person:'Taylor Brooks',ip:'10.24.1.8',time:'09:26:03',summary:'Twelve unsuccessful sign-in attempts within 90 seconds. Compare the source device with previous successful sessions.'},
{id:'IR-2043',title:'Suspicious email attachment',severity:'High',source:'Mail gateway',host:'FIN-WS-014',person:'Avery Morgan',ip:'10.24.3.14',time:'09:12:04',summary:'A message from billing@vendor-demo.example contained Invoice_September.zip. The archive was opened before the outbound transfer.'},
{id:'IR-2044',title:'Unrecognized scheduled task',severity:'High',source:'Endpoint sensor',host:'FIN-WS-014',person:'Avery Morgan',ip:'10.24.3.14',time:'09:17:32',summary:'An unfamiliar task named UpdateCheck was registered shortly after the archive opened. Determine whether the task is approved.'},
{id:'IR-2045',title:'Unusual DNS request pattern',severity:'Medium',source:'DNS resolver',host:'LAB-WS-008',person:'Riley Davis',ip:'10.24.4.8',time:'09:28:12',summary:'The workstation queried sync-lab.example at regular intervals. Check the installed classroom tools before escalating.'},
{id:'IR-2046',title:'New administrator membership',severity:'High',source:'Directory audit',host:'DC-01',person:'Casey Bennett',ip:'10.24.1.10',time:'09:29:46',summary:'A fictional service account was added to a privileged group. Confirm that a documented maintenance change exists.'},
{id:'IR-2047',title:'Removable storage connected',severity:'Medium',source:'Device control',host:'OPS-WS-021',person:'Morgan Lee',ip:'10.24.2.21',time:'09:31:05',summary:'A removable drive was connected to an operations workstation. Review the device inventory and the associated file-access logs.'},
{id:'IR-2048',title:'Blocked inbound connection',severity:'Medium',source:'Perimeter firewall',host:'EDGE-FW-01',person:'Jamie Carter',ip:'10.24.0.1',time:'09:32:40',summary:'The perimeter firewall blocked a connection from documentation address 203.0.113.42. Verify that no allowed follow-up sessions exist.'}
];
const artifacts=[
{id:'EV-04',type:'FILE AUDIT',time:'09:21:09',title:'Archive created',text:'A new archive, quarterly_reports.zip (48.2 MB), was created on FIN-WS-014.',detail:'Path: C:\\Users\\amorgan\\Documents\\quarterly_reports.zip',rank:4},
{id:'EV-01',type:'EMAIL HEADER',time:'09:12:04',title:'Invoice message delivered',text:'Avery Morgan received an unexpected invoice from billing@vendor-demo.example.',detail:'Attachment: Invoice_September.zip · Mailbox: amorgan@northstar.example',rank:1},
{id:'EV-05',type:'NETWORK FLOW',time:'09:24:18',title:'Outbound transfer observed',text:'FIN-WS-014 sent 48.2 MB to 198.51.100.24 over an encrypted connection.',detail:'Source: 10.24.3.14 · Destination port: 443 · Action: allowed',rank:5},
{id:'EV-03',type:'ENDPOINT EVENT',time:'09:17:32',title:'Scheduled task registered',text:'A previously unseen task named UpdateCheck appeared on the same workstation.',detail:'Device: FIN-WS-014 · Account: amorgan · Event: task registration',rank:3},
{id:'EV-06',type:'RESPONSE LOG',time:'09:27:50',title:'Workstation isolated',text:'The response team disconnected FIN-WS-014 from the simulated network.',detail:'Containment: network isolation · Evidence collection: pending',rank:6},
{id:'EV-02',type:'PROCESS RECORD',time:'09:15:41',title:'Attachment opened',text:'The downloaded invoice archive was opened under Avery Morgan’s account.',detail:'Device: FIN-WS-014 · Parent application: file explorer',rank:2}
];
const key='signal-classroom-v1';let state={assignments:{},timeline:[],conclusion:''};let storageOK=true;try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&typeof saved==='object'){state.assignments=saved.assignments&&typeof saved.assignments==='object'?saved.assignments:{};state.timeline=Array.isArray(saved.timeline)?[...new Set(saved.timeline.filter(id=>artifacts.some(a=>a.id===id)))]:[];state.conclusion=typeof saved.conclusion==='string'?saved.conclusion:'';}}catch{storageOK=false}let selected=cases[0].id;let paused=false;let alertCount=24;let tick=0;
function save(){try{localStorage.setItem(key,JSON.stringify(state));return true}catch{storageOK=false;return false}}
function header(){return `<header><a href="index.html" class="brand"><span class="mark">ϟ</span><span>SIGNAL<small>CYBER OPERATIONS</small></span></a><nav aria-label="Workstation screens"><a href="index.html" class="${page==='monitor'?'active':''}">01 / Live monitor</a><a href="triage.html" class="${page==='triage'?'active':''}">02 / Team triage</a><a href="evidence.html" class="${page==='evidence'?'active':''}">03 / Evidence lab</a></nav><div class="header-right"><span class="badge">Training simulation</span><span class="clock" id="clock"></span></div></header>`}
function footer(){return `<footer><span>FICTIONAL DATA ONLY · NORTHSTAR RESEARCH / EXERCISE 07</span><span>${page==='monitor'?'No connection to real networks':'Progress stays in this browser · tabs sync on this workstation'}</span></footer>`}
function title(num,name,desc,actions){return `<div class="titlebar"><div><div class="eyebrow">WORKSTATION ${num} / INCIDENT RESPONSE</div><h1>${name}</h1><p class="sub">${desc}</p></div><div class="actions">${actions}<button class="btn" id="fullscreen">⛶ Full screen</button></div></div>`}
function metrics(data){return `<div class="metrics">${data.map(([label,value,foot,cls])=>`<div class="metric"><div class="metric-label">${label}</div><div class="metric-value ${cls||''}">${value}</div><div class="metric-foot">${foot}</div></div>`).join('')}</div>`}
function network(){let nodes=[['INTERNET',350,42,'EXT / WAN'],['EDGE-FW-01',350,130,'PERIMETER'],['CORE-SW-01',350,225,'10.24.0.0 / 16'],['AUTH-SRV-02',130,220,'IDENTITY'],['DC-01',560,220,'DIRECTORY'],['OPS-WS-021',110,325,'OPERATIONS'],['FIN-WS-014',300,325,'FINANCE'],['LAB-WS-008',485,325,'RESEARCH'],['BACKUP-01',640,325,'STORAGE']];let edges=[[0,1],[1,2],[2,3],[2,4],[2,5],[2,6],[2,7],[4,8]];return `<svg viewBox="0 0 750 390" role="img" aria-label="Animated simulated network map connecting nine devices. Finance workstation highlighted for investigation.">${edges.map(([a,b],i)=>`<path id="p${i}" class="link" d="M${nodes[a][1]},${nodes[a][2]} L${nodes[b][1]},${nodes[b][2]}"/><circle r="3" class="packet"><animateMotion dur="${2+i%3}s" repeatCount="indefinite" begin="-${i}s"><mpath href="#p${i}"/></animateMotion></circle>`).join('')}${nodes.map(([name,x,y,sub],i)=>`<g><circle class="ring" cx="${x}" cy="${y}" r="25" style="animation-delay:-${i/2}s;${i===6?'stroke:#fa777f':''}"/><rect x="${x-18}" y="${y-18}" width="36" height="36" rx="8" class="node ${i===6?'danger':''}"/><path d="M${x-8} ${y-5}h16v9h-16z M${x-4} ${y+8}h8" fill="none" stroke="${i===6?'#fa777f':'#6fe3c4'}"/><text text-anchor="middle" x="${x}" y="${y+39}">${name}</text><text text-anchor="middle" x="${x}" y="${y+55}" style="font-size:10px;fill:#60798c">${sub}</text></g>`).join('')}</svg>`}
const feedTemplates=[['critical','Outbound transfer threshold exceeded','FIN-WS-014 → 198.51.100.24'],['high','Unexpected scheduled task detected','FIN-WS-014 / UpdateCheck'],['high','Multiple sign-in failures','AUTH-SRV-02 / tbrooks'],['info','Endpoint heartbeat received','OPS-WS-021 / Sensor online'],['high','Suspicious attachment quarantined','MAIL-GW-01 / Invoice_September.zip'],['info','Firewall policy enforced','EDGE-FW-01 / Inbound blocked'],['info','Evidence snapshot captured','FIN-WS-014 / Case IR-2041'],['high','Unusual DNS interval detected','LAB-WS-008 / sync-lab.example']];
function alertHTML(item,t){return `<div class="alert ${item[0]}"><span class="severity-bar"></span><div><strong>${item[1]}</strong><small>${item[2]}</small></div><time>${t}</time></div>`}
function renderMonitor(){return title('01','Network activity','Northstar Research · Security operations center',`<span class="live"><span class="dot"></span><span id="streamlabel">${paused?'PAUSED':'LIVE SIMULATION'}</span></span><button class="btn" id="pause">${paused?'Resume':'Pause'}</button>`)+metrics([['Monitored endpoints','128 <small>/ 128</small>','All sensors reporting'],['Events / second','<span id="eps">1,482</span>','Simulated network traffic'],['Alerts received','<span id="alertcount">24</span>','Rolling exercise feed','orange'],['Active investigation','IR–2041','Finance workstation / 1 host','red']])+`<div class="monitor-grid"><section class="panel"><div class="panel-head"><h2>Network topology</h2><span class="meta">9 NODES · 4 SEGMENTS</span></div><div class="network">${network()}</div><div class="legend"><span>Active connection</span><span>Under investigation</span><span>Packet activity</span></div></section><section class="panel"><div class="panel-head"><h2>Incoming alerts</h2><span class="meta">LATEST EVENTS</span></div><div id="feed">${feedTemplates.slice(0,6).map((x,i)=>alertHTML(x,`09:${String(32-i).padStart(2,'0')}:${String(40-i*3).padStart(2,'0')}`)).join('')}</div></section></div><div class="bottom-grid"><section class="panel"><div class="panel-head"><h2>Traffic volume</h2><span class="meta"><span id="throughput">248.6</span> Mb/s / SIMULATED</span></div><div class="traffic" aria-label="Simulated traffic volume chart">${Array.from({length:65},(_,i)=>`<i style="height:${20+(Math.sin(i*3)*.5+.5)*70}%"></i>`).join('')}</div></section><section class="panel"><div class="panel-head"><h2>Protocol distribution</h2><span class="meta">CURRENT WINDOW</span></div><div class="protocols">${[['HTTPS',68],['DNS',19],['SSH',8],['OTHER',5]].map(([x,n])=>`<div class="protocol"><span>${x}</span><span class="bar"><i style="width:${n}%"></i></span><span>${n}%</span></div>`).join('')}</div></section></div>`}
function assignment(id){return state.assignments[id]||{owner:'Unassigned',status:'New',note:''}}
function renderTriage(){let assigned=cases.filter(x=>assignment(x.id).owner!=='Unassigned').length;return title('02','Investigation queue','Review the signal. Assign an analyst. Leave a clear next step.',`<a class="btn" href="evidence.html" target="_blank" rel="noopener">Open evidence lab ↗</a>`)+metrics([['Open cases',cases.filter(x=>assignment(x.id).status!=='Resolved').length,'Northstar Research'],['Critical priority','01','Immediate review','red'],['Assigned to analysts',String(assigned).padStart(2,'0'),'Team workload'],['Evidence to correlate','06','Linked to IR-2041']])+`<div class="workspace"><section class="panel"><div class="panel-head"><h2>Alert casebook</h2><span class="meta">8 RECORDS / SELECT A CASE</span></div><div class="tablewrap"><table><thead><tr><th scope="col">CASE / DETECTION</th><th scope="col">PRIORITY</th><th scope="col">AFFECTED USER</th><th scope="col">ASSIGNEE</th><th scope="col">STATUS</th></tr></thead><tbody>${cases.map(c=>`<tr class="${c.id===selected?'selected':''}"><td><button class="casebutton" data-case="${c.id}" aria-pressed="${c.id===selected}"><b>${c.title}</b><small>${c.id} · ${c.time}</small></button></td><td><span class="pill ${c.severity}">${c.severity}</span></td><td>${c.person}<div class="meta" style="margin-top:6px">${c.host}</div></td><td>${esc(assignment(c.id).owner)}</td><td>${esc(assignment(c.id).status)}</td></tr>`).join('')}</tbody></table></div><div class="panel-head"><span class="meta">ALL IDENTITIES AND RECORDS ARE FABRICATED</span></div></section><aside class="panel" id="case-detail">${detailHTML()}</aside></div><section class="panel" style="margin-top:22px"><div class="panel-head"><h2>Response team</h2><span class="meta">FICTIONAL ANALYST ROSTER</span></div><div class="team">${members.slice(1).map((m,i)=>`<div class="member"><span class="avatar">${m.split(' ').map(x=>x[0]).join('')}</span><span>${m}<small>${['Incident lead','Network analyst','Endpoint analyst','Evidence specialist'][i]} · ${cases.filter(c=>assignment(c.id).owner===m).length} assigned</small></span></div>`).join('')}</div></section>`}
function detailHTML(){const c=cases.find(c=>c.id===selected),a=assignment(c.id);return `<div class="panel-head"><h2>Case details</h2><span class="meta">${c.id}</span></div><form class="detail" id="caseform"><span class="pill ${c.severity}">${c.severity}</span><h3>${c.title}</h3><p style="font-size:14px">${c.summary}</p><dl><dt>Device</dt><dd>${c.host}</dd><dt>IP address</dt><dd>${c.ip}</dd><dt>Source</dt><dd>${c.source}</dd></dl><label for="owner">Assign to</label><select id="owner">${members.map(m=>`<option ${m===a.owner?'selected':''}>${m}</option>`).join('')}</select><label for="status">Case status</label><select id="status">${['New','Investigating','Contained','Resolved'].map(s=>`<option ${s===a.status?'selected':''}>${s}</option>`).join('')}</select><label for="note">Analyst note</label><textarea id="note" maxlength="600" placeholder="What did you observe? What should the team check next?">${esc(a.note)}</textarea><button class="btn primary" style="margin-top:16px;width:100%" type="submit">Save case update</button><div class="saved" id="save-message" role="status">${storageOK?'Saved on this workstation only.':'Browser storage unavailable; progress lasts this session.'}</div></form>`}
function artifactHTML(a,inTimeline=false,i=0){return `<div class="artifact" ${inTimeline?'':`draggable="true" data-drag="${a.id}"`}><div class="row"><code>${a.id} / ${a.type}</code><span class="meta">${a.time}</span></div><h3>${a.title}</h3><p>${a.text}</p><details><summary class="meta" style="cursor:pointer;margin-bottom:12px">View record</summary><p>${a.detail}</p></details><div class="row">${inTimeline?`<div class="actions"><button class="btn small" data-up="${a.id}" aria-label="Move ${a.title} earlier" ${i===0?'disabled':''}>↑ Earlier</button><button class="btn small" data-down="${a.id}" aria-label="Move ${a.title} later" ${i===state.timeline.length-1?'disabled':''}>↓ Later</button></div><button class="btn small" data-remove="${a.id}" aria-label="Remove ${a.title} from timeline">Remove</button>`:`<span class="meta">FIN-WS-014</span><button class="btn small" data-add="${a.id}">+ Add to timeline</button>`}</div></div>`}
function renderEvidence(){return title('03','Reconstruct the incident','IR-2041 · Connect the evidence from first contact to containment.',`<button class="btn" id="reset">Reset timeline</button>`)+`<div class="evidence-grid"><section class="panel"><div class="panel-head"><h2>Evidence tray</h2><span class="meta">${6-state.timeline.length} REMAINING</span></div><div class="evidence-list">${artifacts.filter(a=>!state.timeline.includes(a.id)).map(a=>artifactHTML(a)).join('')||'<div class="empty">All six artifacts are on your timeline. Check their order.</div>'}</div></section><section class="panel"><div class="panel-head"><h2>Incident timeline</h2><span class="meta">${state.timeline.length} / 6 PLACED</span></div><div class="timeline-list" id="dropzone">${state.timeline.length?state.timeline.map((id,i)=>`<div class="timeline-item"><span class="step">${i+1}</span>${artifactHTML(artifacts.find(a=>a.id===id),true,i)}</div>`).join(''):'<div class="empty"><div class="eyebrow">BUILD THE SEQUENCE</div>Drag evidence here, or use<br>“Add to timeline” on each record.<br><br><span class="meta">Arrange from earliest to latest.</span></div>'}</div><div class="panel-head"><button class="btn primary" id="check">Check sequence</button><span class="meta">ORDER BY EVIDENCE TIME</span></div><div class="result" id="sequence-result" role="status">Use Earlier and Later to reorder placed artifacts.</div></section><aside class="panel"><div class="panel-head"><h2>Investigation brief</h2></div><div class="brief"><span class="pill Critical">IR-2041 / Critical</span><h3 style="margin-top:20px">Follow the evidence</h3><p>A finance workstation sent an unexpected outbound transfer. Reconstruct what happened before the response team isolated it.</p><div class="fact"><small>AFFECTED USER</small>Avery Morgan</div><div class="fact"><small>DEVICE / ADDRESS</small>FIN-WS-014<br><span class="meta">10.24.3.14</span></div><div class="fact"><small>YOUR OBJECTIVE</small>Identify the entry point, suspicious activity, transfer, and containment.</div><label for="conclusion" style="display:block;margin:22px 0 10px;font-size:14px">Investigation summary</label><textarea id="conclusion" maxlength="1000" placeholder="The likely entry point was… The evidence shows…">${esc(state.conclusion)}</textarea><button class="btn" id="save-conclusion" style="margin-top:12px;width:100%">Save summary</button><div class="saved" id="conclusion-status" role="status"></div><a href="triage.html" target="_blank" rel="noopener" class="btn" style="display:block;text-align:center;margin-top:15px">Open team triage ↗</a></div></aside></div>`}
function updateCase(id,owner,status,note){if(!cases.some(c=>c.id===id)||!members.includes(owner)||!['New','Investigating','Contained','Resolved'].includes(status)||typeof note!=='string'||note.length>600)throw Error('Invalid case update');state.assignments[id]={owner,status,note};save();render();return {id,...state.assignments[id]}}
function setTimeline(ids){if(!Array.isArray(ids)||new Set(ids).size!==ids.length||ids.some(id=>!artifacts.some(a=>a.id===id)))throw Error('Invalid artifact IDs');captureSummary();state.timeline=ids;save();render();return {timeline:state.timeline}}
function captureSummary(){if($('#conclusion'))state.conclusion=$('#conclusion').value}
function render(){document.title=`Signal / ${page==='monitor'?'Live monitor':page==='triage'?'Team triage':'Evidence lab'}`;$('#app').innerHTML=header()+`<main>${page==='monitor'?renderMonitor():page==='triage'?renderTriage():renderEvidence()}${footer()}</main>`;$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{$('#fullscreen').textContent='Use browser full screen'}};clock();bind();if(page==='monitor')applyPause()}
function bind(){if(page==='monitor'){$('#pause').onclick=()=>{paused=!paused;applyPause()};return}if(page==='triage'){document.querySelectorAll('[data-case]').forEach(b=>b.onclick=()=>{if($('#caseform')){state.assignments[selected]={owner:$('#owner').value,status:$('#status').value,note:$('#note').value};save()}selected=b.dataset.case;render()});$('#caseform').onsubmit=e=>{e.preventDefault();updateCase(selected,$('#owner').value,$('#status').value,$('#note').value);$('#save-message').textContent=storageOK?'Case updated · saved on this workstation.':'Case updated for this session; browser storage unavailable.'};return}document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>setTimeline([...state.timeline,b.dataset.add]));document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>setTimeline(state.timeline.filter(id=>id!==b.dataset.remove)));for(const dir of ['up','down'])document.querySelectorAll(`[data-${dir}]`).forEach(b=>b.onclick=()=>{let ids=[...state.timeline],i=ids.indexOf(b.dataset[dir]),j=i+(dir==='up'?-1:1);if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];setTimeline(ids)});document.querySelectorAll('[data-drag]').forEach(el=>el.ondragstart=e=>e.dataTransfer.setData('text/plain',el.dataset.drag));$('#dropzone').ondragover=e=>e.preventDefault();$('#dropzone').ondrop=e=>{e.preventDefault();let id=e.dataTransfer.getData('text/plain');if(artifacts.some(a=>a.id===id)&&!state.timeline.includes(id))setTimeline([...state.timeline,id])};$('#check').onclick=()=>{$('#sequence-result').textContent=state.timeline.length<6?'Add all six artifacts before checking the sequence.':state.timeline.every((id,i)=>artifacts.find(a=>a.id===id).rank===i+1)?'Sequence verified. Email → attachment opened → task registered → archive created → outbound transfer → containment. Now summarize what the evidence supports.':'Not quite. Compare the timestamps and move the earlier events toward the top.'};$('#reset').onclick=()=>{if(!state.timeline.length)return;if(confirm('Return all artifacts to the evidence tray? Your written summary will be kept.'))setTimeline([])};$('#save-conclusion').onclick=()=>{captureSummary();save();$('#conclusion-status').textContent=storageOK?'Summary saved on this workstation.':'Summary kept for this session only.'};$('#conclusion').oninput=()=>{captureSummary();save()}}
function clock(){if($('#clock'))$('#clock').textContent=new Date().toLocaleTimeString('en-GB')+' LOCAL'}
function applyPause(){document.body.classList.toggle('paused',paused);document.body.classList.toggle('simulation-running',!paused);$('#pause').textContent=paused?'Resume':'Pause';$('#streamlabel').textContent=paused?'PAUSED':'LIVE SIMULATION';let svg=$('.network svg');if(paused)svg.pauseAnimations?.();else svg.unpauseAnimations?.()}
render();setInterval(clock,1000);setInterval(()=>{if(page!=='monitor'||paused)return;tick++;alertCount++;$('#alertcount').textContent=alertCount;$('#eps').textContent=(1350+Math.floor(Math.random()*400)).toLocaleString();$('#throughput').textContent=(220+Math.random()*60).toFixed(1);$('#feed').insertAdjacentHTML('afterbegin',alertHTML(feedTemplates[tick%feedTemplates.length],new Date().toLocaleTimeString('en-GB')));while($('#feed').children.length>6)$('#feed').lastElementChild.remove();document.querySelectorAll('.traffic i').forEach(i=>i.style.height=(18+Math.random()*78)+'%')},4500);
window.addEventListener('storage',e=>{if(e.key!==key||!e.newValue)return;try{const s=JSON.parse(e.newValue);if(s.assignments&&Array.isArray(s.timeline)){state=s;if(page==='triage'&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))render();}}catch{}});
if(document.modelContext?.registerTool){const tool=page==='triage'?{name:'update_investigation_case',description:'Assign a fictional case, set status, and save an analyst note on this workstation.',inputSchema:{type:'object',properties:{id:{type:'string',enum:cases.map(c=>c.id)},owner:{type:'string',enum:members},status:{type:'string',enum:['New','Investigating','Contained','Resolved']},note:{type:'string',maxLength:600}},required:['id','owner','status','note'],additionalProperties:false},execute:async i=>updateCase(i.id,i.owner,i.status,i.note)}:page==='evidence'?{name:'arrange_evidence_timeline',description:'Set the order of fictional evidence artifacts on the visible incident timeline.',inputSchema:{type:'object',properties:{ids:{type:'array',items:{type:'string',enum:artifacts.map(a=>a.id)},uniqueItems:true}},required:['ids'],additionalProperties:false},execute:async i=>setTimeline(i.ids)}:null;if(tool)try{Promise.resolve(document.modelContext.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}})).catch(()=>{})}catch{}}
