/* ============================================================
   GLOSSARY
   One picture holds all of it together: the network is a city and
   you are a letter being carried through it. Every entry leans on
   that image so the pieces reinforce each other instead of being
   fifty-five unrelated comparisons.

   t = term, g = tags, k = tier, m = metaphor, h = how it really
   works, i = what it means inside the game.
   ============================================================ */
const GTAGS = {
  hardware:'Hardware', packet:'Packet', addressing:'Addressing', layer2:'Layer 2',
  layer3:'Layer 3', protocol:'Protocol', config:'Config', security:'Security', trouble:'Trouble'
};

const GLOSS = [
{t:'Packet', g:['packet','protocol'], k:0,
 m:'A letter in an envelope. The message is inside; everything needed to deliver it is written on the outside.',
 h:'Big files are too large to send in one piece, so computers chop them into packets. Each travels on its own and they are reassembled at the far end. If one is lost, only that piece is resent.',
 i:'You are the packet.'},
{t:'Header', g:['packet','addressing'], k:0,
 m:'The writing on the envelope: who it is from, who it is going to, and any handling instructions.',
 h:'Headers sit in front of the data. Different devices read different parts, and some rewrite parts before passing the packet along.',
 i:'The bands you wear. Watch which one a device lights up — that is what it can see.'},
{t:'Payload', g:['packet'], k:0,
 m:'The letter inside the envelope. The carrier never reads it. They only read the outside.',
 h:'Devices along the way almost never look at the payload. They only need the header to decide where to send the packet next.'},
{t:'Protocol', g:['protocol'], k:0,
 m:'Two people agreeing to speak the same language before a conversation starts.',
 h:'A protocol defines the order of messages, what each part means, and what to do when something goes wrong. Both sides have to follow the same one.'},
{t:'Topology', g:['hardware'], k:0,
 m:'The street map of the city, showing which roads connect which buildings.',
 h:'Topology decides how traffic can flow, where bottlenecks form, and what breaks when a single link fails.',
 i:'What the architect builds and the packet cannot see.'},
{t:'Bandwidth', g:['hardware'], k:0,
 m:'The number of lanes on a road. More lanes move more cars at once, but no single car goes faster.',
 h:'Measured in bits per second. It is about capacity, not speed. A crowded high-bandwidth link can still feel slow.'},
{t:'Latency', g:['trouble'], k:0,
 m:'How long the drive takes. A wider road does not shorten the distance.',
 h:'Latency comes from physical distance, from the time each device takes to decide, and from waiting in line behind other traffic.',
 i:'Every device you pass costs a beat.'},
{t:'Link', g:['hardware'], k:0,
 m:'One stretch of road between two buildings.',
 h:'A link can be copper, fiber, or wireless. Every link has a maximum useful length before the signal weakens too much.',
 i:'The line you travel along.'},
{t:'Repeater', g:['hardware'], k:0,
 m:'A relay runner who takes the message and sprints the next stretch at full speed.',
 h:'Signals fade as they travel. A repeater rebuilds the signal to full strength and sends it onward. It makes no decisions about direction.',
 i:'Buys you distance, not hops. It does not give you more TTL.'},
{t:'Hub', g:['hardware','layer2'], k:0,
 m:'Someone who reads your letter aloud to the entire building instead of walking it to one office.',
 h:'A hub has no memory and makes no decisions. Everything arriving on one port goes out all the others. Two messages arriving at once collide and both are ruined.',
 i:'Offers you every exit, because it has no idea which one is right.'},
{t:'Collision', g:['trouble','layer2'], k:0,
 m:'Two people shouting at once in a hallway. Nobody can make out either message, so both have to repeat.',
 h:'On shared media only one device can transmit at a time. When two try, the signals overlap and become unreadable.'},
{t:'Packet Loss', g:['trouble','packet'], k:0,
 m:'Letters that never show up. Sometimes the road flooded, sometimes someone threw them away on purpose.',
 h:'Loss comes from congestion, faulty hardware, weak signals, or deliberate blocking. TCP notices and resends; UDP does not notice at all.',
 i:'Every death you suffer is packet loss from the network\u2019s point of view.'},

{t:'MAC Address', g:['addressing','layer2'], k:1,
 m:'A person\u2019s face. It does not change when they move to a new city, and it only helps if you are in the same room as them.',
 h:'Every network adapter is manufactured with a unique MAC address burned in. It is only useful inside one local network — once traffic crosses a router, the MAC is replaced.',
 i:'One of your bands. Switches read it; routers tear it off and staple a new one on.'},
{t:'Switch', g:['hardware','layer2'], k:1,
 m:'A building mailroom clerk who learns where everyone sits. The first time a name is new they walk the halls asking. After that they walk straight to the desk.',
 h:'A switch reads the MAC address and sends the frame out only the port where that device lives. It learns by remembering which port each address arrived from.',
 i:'Reads your MAC band and is completely blind to your IP.'},
{t:'MAC Address Table', g:['layer2','config'], k:1,
 m:'The mailroom clerk\u2019s seating chart, filled in by watching who walks in from which door.',
 h:'When a frame arrives, the switch records the sender\u2019s MAC and the port it came from. That is how the table fills itself with no configuration at all.'},
{t:'Frame', g:['packet','layer2'], k:1,
 m:'Your envelope tucked inside a second envelope addressed to the next carrier only.',
 h:'The outer wrapper carries MAC addresses and is thrown away and rebuilt at every router. The packet inside keeps its IP addresses the whole trip.'},
{t:'Broadcast', g:['layer2','protocol'], k:1,
 m:'Shouting a question down a hallway so everyone hears it, hoping the right person answers.',
 h:'Broadcasts are useful for finding things when you do not know who to ask. They stop at routers, which keeps them from flooding the entire internet.',
 i:'A free action that costs a turn.'},
{t:'Broadcast Domain', g:['layer2'], k:1,
 m:'Everyone within earshot of your shout. The walls of the building are where your voice stops.',
 h:'Switches pass broadcasts along, so they extend the domain. Routers block them, so a router is where one domain ends and another begins.'},
{t:'Broadcast Storm', g:['trouble','layer2'], k:1,
 m:'A rumour in a circular hallway. Everyone keeps repeating it to the next person forever, and no real conversation can happen over the noise.',
 h:'If switches are wired in a loop, a broadcast goes around and around, copied each time. There is no hop counter to stop it, so it grows until nothing else gets through.'},
{t:'VLAN', g:['layer2','config','security'], k:1,
 m:'Coloured badges in one office. Blue and red walk the same halls but cannot enter each other\u2019s rooms, even though nothing physical separates them.',
 h:'Ports get assigned a VLAN number. Traffic in one VLAN cannot reach another without going through a router, even on the same switch.',
 i:'A door of the wrong colour stays greyed out no matter how correct everything else is.'},
{t:'Access Port', g:['config','layer2'], k:1,
 m:'A doorway into one specific colour-coded room. You come out wearing that colour and nothing else.',
 h:'Access ports are where regular computers plug in. The switch removes the VLAN tag before handing traffic over, so the computer never knows VLANs exist.'},
{t:'Trunk Port', g:['config','layer2'], k:1,
 m:'A shared hallway every badge colour may walk down, as long as everyone keeps their badge visible.',
 h:'Trunks connect switches to each other. Each frame keeps a tag saying which VLAN it belongs to so the far end can sort it correctly.'},
{t:'Spanning Tree (STP)', g:['protocol','layer2','trouble'], k:1,
 m:'Closing off one hallway in a circular building so people stop walking in circles. The hallway stays there, ready to reopen if another closes.',
 h:'Switches talk to each other, discover loops, and deliberately block one path. If an active link fails, a blocked link wakes up and takes over.'},

{t:'IP Address', g:['addressing','layer3'], k:2,
 m:'A street address. Unlike a face, it changes when you move, and it is what lets someone across the world find you.',
 h:'IP addresses have a network part and a host part. The network part says which neighbourhood, the host part says which house. Routers care about the neighbourhood.',
 i:'One of your bands. Routers read it; switches are blind to it.'},
{t:'Router', g:['hardware','layer3'], k:2,
 m:'A post office that ships between cities. It does not care about the name on the inner envelope, only which city it belongs to.',
 h:'A router reads the IP address, decides which network it belongs to, rebuilds the local delivery wrapper, and sends it on.',
 i:'The only piece that moves you between regions. Costs one hop of TTL.'},
{t:'Subnet', g:['addressing','layer3'], k:2,
 m:'One neighbourhood inside a city. Everyone there shares a section of address, and you can reach a neighbour without involving the post office.',
 h:'Splitting a big network into subnets keeps broadcast noise contained and makes it possible to apply different rules to different groups.'},
{t:'Subnet Mask', g:['addressing','layer3','config'], k:2,
 m:'A card with a window cut in it. Lay it over two addresses and only part shows through. If the visible parts match you are neighbours. If not, you need the post office.',
 h:'The mask marks where the network part of the address ends. A device compares its own address and the destination through the mask to decide: deliver locally, or hand it to the gateway.',
 i:'When two exits are both legal, running the mask yourself is the only way to know which one is right.'},
{t:'Default Gateway', g:['addressing','layer3','config'], k:2,
 m:'The mailbox on the corner. You do not need to know how the mail system works — just where to drop anything going out of town.',
 h:'When the mask says the destination is not local, the device hands the packet to its gateway and trusts it to figure out the rest.',
 i:'A missing gateway means you can never leave your own region.'},
{t:'Routing Table', g:['layer3','config'], k:2,
 m:'A wall chart at the post office: for this destination city, use that truck.',
 h:'The router checks the destination against its table and picks the most specific matching entry. If nothing matches and there is no default route, the packet is dropped.'},
{t:'Static Route', g:['layer3','config'], k:2,
 m:'A sticky note on the wall chart that overrides the printed instructions.',
 h:'Static routes are predictable and never change on their own, which makes them useful in small networks and dangerous when the network changes and nobody updates them.',
 i:'The architect\u2019s steering wheel.'},
{t:'Blackhole Route', g:['layer3','trouble','config'], k:2,
 m:'A mail chute that goes straight to the shredder. Letters go in and nothing comes out, and nobody gets a complaint.',
 h:'Sometimes used on purpose to block unwanted traffic, sometimes created by a typo. Either way, nothing reports back.'},
{t:'Hop', g:['packet','layer3'], k:2,
 m:'One leg of a relay race. Each handoff is a hop.',
 h:'Hops are counted to measure how far a packet has travelled and to stop it circling forever.',
 i:'Every router costs one. Switches do not.'},
{t:'TTL (Time To Live)', g:['packet','trouble'], k:2,
 m:'A tank of gas with a fixed number of stops in it. When it runs dry, the letter gets thrown out wherever it happens to be.',
 h:'Every router subtracts one from the TTL. At zero the packet is discarded and an error goes back to the sender. This is what stops routing loops lasting forever.',
 i:'Your life bar, and how the architect sets difficulty.'},
{t:'NAT', g:['layer3','addressing','security'], k:2,
 m:'A hotel front desk. Outgoing mail all shows the hotel\u2019s address, and the desk keeps a list of which reply goes to which room.',
 h:'The router swaps the private source address for its own public one and records the swap. When the reply returns it looks up the record and forwards it internally.'},
{t:'Ping', g:['trouble','protocol'], k:2,
 m:'Knocking on a door and listening for a knock back. It does not tell you what is inside, only that someone is home.',
 h:'Ping sends a small message and waits for a reply, reporting the round trip time or reporting that nothing answered.'},
{t:'Traceroute', g:['trouble','protocol'], k:2,
 m:'Sending letters with one stop of gas, then two, then three, and writing down who mails each one back to you.',
 h:'It sends packets with deliberately small TTL values. Each router that discards one reports back, exposing the path a hop at a time.'},

{t:'ARP', g:['protocol','addressing','layer2'], k:3,
 m:'Standing in the hallway and shouting "who is at desk 12?" and waiting for someone to raise their hand.',
 h:'The request goes to everyone in the local network. The device with that IP answers with its MAC, and the answer is cached so you do not have to shout again.',
 i:'Costs a turn. Everyone nearby hears the question and the answer, which is exactly what a spoofer exploits.'},
{t:'DHCP', g:['protocol','addressing','config'], k:3,
 m:'A hotel front desk assigning you a room number when you check in. You do not pick it — you are given one for the length of your stay.',
 h:'A device with no address broadcasts a request. A DHCP server offers an address, a mask and a gateway. The device accepts and the settings are leased for a set period.',
 i:'Some levels spawn you with no address. Finding DHCP is your first objective.'},
{t:'DNS', g:['protocol','addressing'], k:3,
 m:'A phone book. You know the person\u2019s name, so you look up the number before you can call.',
 h:'Your device asks a resolver for the address behind a name. The resolver may ask other servers up the chain. The answer is cached so the next lookup is instant.',
 i:'Spawn knowing only a name and you must detour to trade it for an address.'},
{t:'Port Number', g:['addressing','protocol'], k:3,
 m:'The apartment number after the street address. The building is the machine; the apartment is the program inside it.',
 h:'One computer runs many services at once. Ports keep them separate — web traffic uses 80 and 443, secure shell uses 22.',
 i:'Your key\u2019s shape. Doors are cut for specific shapes.'},
{t:'TCP', g:['protocol','packet'], k:3,
 m:'Certified mail. You get a signature confirming it arrived, and if it goes missing it is sent again.',
 h:'TCP starts with a three-step handshake, numbers every piece so they reassemble in order, and requires acknowledgements. Anything unacknowledged is retransmitted.',
 i:'Costs turns up front, gives you a checkpoint. The safe route.'},
{t:'UDP', g:['protocol','packet'], k:3,
 m:'Tossing a postcard in the mailbox. It probably arrives. Nobody tells you either way.',
 h:'No handshake, no acknowledgement, no retransmission. That makes it fast and light, which is why live video and games use it.',
 i:'Starts instantly with no safety net. The speedrun.'},
{t:'Handshake', g:['protocol'], k:3,
 m:'Saying hello, hearing hello back, and confirming you heard it, all before the real conversation starts.',
 h:'TCP uses three messages to confirm both sides can send and receive before any data moves. It costs time up front and buys reliability afterwards.'},
{t:'Encapsulation', g:['packet','protocol'], k:3,
 m:'An envelope inside an envelope inside an envelope. Each carrier opens only their own layer.',
 h:'Each layer of the network adds its own header. The receiving side unwraps them in reverse order until the original data is exposed.',
 i:'Why you wear multiple bands, and why different devices light up different ones.'},

{t:'Firewall', g:['security','hardware'], k:4,
 m:'A security guard at the door with a clipboard. Your name is on the list or it is not.',
 h:'Firewalls check source, destination, port and protocol against a rule set. The first matching rule wins, and most sets end by denying anything not explicitly allowed.',
 i:'Spotlights your port band. Denied exits stay greyed with the reason written on them.'},
{t:'Stateful Firewall', g:['security'], k:4,
 m:'A guard who remembers stamping your hand on the way out, so they wave you back in without checking the list again.',
 h:'It tracks active connections. Return traffic belonging to an approved outbound connection is allowed automatically.'},
{t:'ACL', g:['security','config'], k:4,
 m:'The guest list at the door, read top to bottom. The first line that matches your name decides everything, so the order matters enormously.',
 h:'ACLs are applied to a specific interface in a specific direction. A rule that would allow you does nothing if a deny rule above it matches first.'},
{t:'IDS', g:['security'], k:4,
 m:'A security camera. It records you and alerts someone, but it cannot physically stop you walking through.',
 h:'An IDS sits alongside the traffic flow and compares what it sees against known bad patterns. It detects and reports but does not block.'},
{t:'IPS', g:['security'], k:4,
 m:'A guard standing in the doorway instead of a camera on the wall. They see the same thing, but they can put an arm out.',
 h:'An IPS sits directly in the traffic path so it can drop packets. That power is also its risk: a false positive blocks legitimate traffic.'},
{t:'ARP Spoofing', g:['security','trouble','layer2'], k:4,
 m:'You shout "who is at desk 12?" and a stranger raises their hand. You hand them your mail and walk away satisfied.',
 h:'ARP has no way to verify answers, so whoever replies is believed. An attacker who answers first receives traffic meant for someone else, reads it, and passes it along so nobody notices.'},
{t:'Man in the Middle', g:['security','trouble'], k:4,
 m:'Someone intercepting letters between two friends, reading each one, resealing it, and sending it on. Both keep writing and neither suspects.',
 h:'The attacker convinces both sides they are the other one. Because traffic still arrives, nothing looks broken, which is what makes it hard to notice.'},
{t:'VPN Tunnel', g:['security','protocol'], k:4,
 m:'A sealed diplomatic pouch. It travels the same public roads as everything else, but nobody along the way can open it.',
 h:'The original packet is encrypted and wrapped inside a new one. Devices in between can see that something is being carried but cannot read what it is.'},
{t:'Proxy', g:['security','hardware'], k:4,
 m:'An assistant who reads what you want, writes their own letter asking for it, and hands you the reply. The far end never learns your name.',
 h:'The proxy terminates your connection and opens a new one. That lets it filter content, cache repeated requests, and hide who originally asked.'},
{t:'Encryption', g:['security'], k:4,
 m:'Writing the letter in a code that only you and your friend know. Anyone who steals it holds nothing but nonsense.',
 h:'The sender scrambles the data with a key and the receiver unscrambles it with a matching one. Anyone in between sees only unreadable output.'}
];
