'use strict';
const $=s=>document.querySelector(s), main=$('#main'), {people,companies,docs}=WORLD;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const localImages=new Set(WORLD.localImages||['morgan-vale','tessa-brooks','dev-malik']);
const imagePath=n=>(localImages.has(n)?'assets/':'../osint/assets/')+n+'.jpg';
const picture=(n,alt,cls='')=>`<img class="${cls}" src="${imagePath(n)}" alt="${esc(alt)}" loading="lazy">`;
const avatar=id=>picture(people[id].image,people[id].name,'avatar');
function scenePhoto(name,alt,cls='post-photo'){return `<button type="button" class="photo-open" data-photo="${esc(name)}" data-photo-alt="${esc(alt)}" aria-label="Enlarge photo: ${esc(alt)}">${picture(name,alt,cls)}</button>`;}

let state=loadNotebookState(),account=null;
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3500);}
function record(label,source=location.hash){return `<button class="record" data-record="${esc(label)}" data-source="${esc(source)}">＋ Record finding</button>`;}
function mini(id){const p=people[id];return `<a class="mini-person" href="#/person/${id}">${avatar(id)}<div><strong>${esc(p.name)}</strong><p>${esc(p.headline)}</p></div></a>`;}
function companyLink(id){return `<a href="#/company/${id}">${esc(companies[id].name)}</a>`;}
function sidebar(ids=Object.keys(people).slice(0,4)){return `<aside class="sidebar card"><h2>People in this network</h2>${ids.map(mini).join('')}<p class="meta"><a href="#/people">Explore all professionals →</a></p></aside>`;}
function postCard(owner,p){return `<article class="card"><div class="post-author"><a href="#/person/${owner}">${avatar(owner)}</a><div><a href="#/person/${owner}"><strong>${esc(people[owner].name)}</strong></a><p>${esc(people[owner].headline)}</p><p>${esc(p.date)} · Public</p></div></div><p class="post-text">${esc(p.text)}</p>${p.image?scenePhoto(p.image,p.imageAlt||p.text):''}${p.comments.length?`<div class="comments">${p.comments.map(([id,text])=>`<div class="comment"><a href="#/person/${id}">${avatar(id)}</a><p><a href="#/person/${id}">${esc(people[id].name)}</a><br>${esc(text)}</p></div>`).join('')}</div>`:''}<div class="post-footer"><a class="meta" href="#/post/${p.id}">Open post</a>${record(people[owner].name+' · '+p.date,'#/post/'+p.id)}</div></article>`;}

function companyMark(id){return `<span class="company-mark" aria-hidden="true">${esc(companies[id].name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</span>`;}
function companyPostCard(id,post){
  const c=companies[id];
  return `<article class="card company-post"><div class="post-author"><a href="#/company/${id}" aria-label="${esc(c.name)}">${companyMark(id)}</a><div>${companyLink(id)}<p>${esc(c.sector)}</p><p>${esc(post.date)} · Public</p></div></div>${post.title?`<h3>${esc(post.title)}</h3>`:''}<p class="post-text">${esc(post.text)}</p>${post.image?scenePhoto(post.image,post.imageAlt):''}${post.comments?.length?`<div class="comments">${post.comments.map(([who,text])=>`<div class="comment"><a href="#/person/${who}">${avatar(who)}</a><p><a href="#/person/${who}">${esc(people[who].name)}</a><br>${esc(text)}</p></div>`).join('')}</div>`:''}<div class="post-footer"><a class="meta" href="#/company-post/${post.id}">Open update</a>${record(c.name+' · '+(post.title||post.date),'#/company-post/'+post.id)}</div></article>`;
}
function companyUpdatePage(id){
  for(const [companyId,c] of Object.entries(companies)){
    const post=c.updates.find(p=>p.id===id);
    if(post){main.innerHTML=`<div class="layout"><section><p><a href="#/company/${companyId}">← ${esc(c.name)}</a></p><h1 class="update-page-title">${esc(post.title||c.name+' update')}</h1>${companyPostCard(companyId,post)}</section>${sidebar(Object.keys(people).filter(pid=>people[pid].company===companyId).concat(post.comments.map(([pid])=>pid)).filter((pid,i,all)=>all.indexOf(pid)===i).slice(0,4))}</div>`;return;}
  }
  missing();
}

function feed(){
  const feedItems=['dana','morgan','sam','tessa','dev','ellis','corey','kai','lena'].map((id,i)=>postCard(id,people[id].posts[0])+(i===1?companyPostCard('current',companies.current.updates[0]):i===4?companyPostCard('riverspan',companies.riverspan.updates[0]):''));
  main.innerHTML=`<div class="feed-layout"><aside class="sidebar"><section class="feed-intro"><p class="eyebrow">Your next connection</p><h1>Good work.<br>Real conversations.</h1><p class="meta">Ideas from the people building things around you.</p><a href="#/people">Explore the network →</a></section><div class="card" style="margin-top:20px"><h2>Organizations</h2>${['cedar','open','press','next'].map(id=>`<p>${companyLink(id)}</p>`).join('')}<h2>Across the region</h2>${['current','lockside','riverspan'].map(id=>`<p>${companyLink(id)}</p>`).join('')}<a class="meta" href="#/companies">Explore all organizations →</a></div></aside><section><div class="section-head"><h2>From your professional community</h2><span class="meta">Latest posts</span></div>${feedItems.join('')}</section>${sidebar(['lena','sam','morgan','tessa'])}</div>`;
}
function profile(id){if(!own(people,id))return missing();const p=people[id];main.innerHTML=`<div class="layout"><div><section class="card profile-card"><div class="cover"></div><div class="profile-info">${avatar(id)}<h1>${esc(p.name)}</h1><p class="headline">${esc(p.headline)}</p><p class="meta">${esc(p.location)} · ${companyLink(p.company)}</p><p class="profile-stats">${180+Object.keys(people).indexOf(id)*43} connections · Public profile</p><p>${esc(p.bio)}</p>${record(p.name+' · Profile')}</div></section><section><div class="section-head"><h2>Recent post</h2><span class="meta">Public activity</span></div>${postCard(id,p.posts[0])}<details class="disclosure"><summary>Show earlier posts (${p.posts.length-1})</summary>${p.posts.slice(1).map(post=>postCard(id,post)).join('')}</details></section><section class="card"><h2>Experience</h2>${p.history.map(h=>`<div class="history"><h3>${esc(h.role)}</h3>${companyLink(h.company)}<p class="meta">${esc(h.years)}</p><p>${esc(h.detail)}</p></div>`).join('')}${record(p.name+' · Experience')}</section><section class="card"><h2>Activity · Comments</h2>${p.activity.map(([company,text])=>`<div class="activity-item"><p class="meta">${esc(p.name)} commented on ${companyLink(company)}’s update</p><p>“${esc(text)}”</p><a href="#/company/${company}">View company conversation →</a></div>`).join('')}${record(p.name+' · Comment activity')}</section><section class="card"><h2>Education</h2>${p.education.map(e=>`<div class="history"><h3>${esc(e.school)}</h3><p>${esc(e.degree)}</p><p class="meta">${esc(e.years)}</p></div>`).join('')}${record(p.name+' · Education')}</section><section class="card"><h2>Skills</h2><div class="tags">${p.skills.map(s=>`<span>${esc(s)}</span>`).join('')}</div></section></div>${sidebar(p.connections)}</div>`;}
function company(id){
  if(!own(companies,id))return missing();
  const c=companies[id],employees=Object.keys(people).filter(k=>people[k].company===id),contributors=Object.entries(people).flatMap(([pid,p])=>p.activity.filter(a=>a[0]===id).map(([,text])=>[pid,text]));
  const former=Object.keys(people).filter(k=>!employees.includes(k)&&people[k].history.some(h=>h.company===id));
  main.innerHTML=`<div class="layout"><div><section class="card">${scenePhoto(c.image,c.imageAlt||c.name,'company-cover')}<p class="eyebrow">${esc(c.sector)}</p><h1>${esc(c.name)}</h1><p class="headline">${esc(c.tag)}</p><p class="meta">${esc(c.location)} · ${esc(c.size)} employees</p><p>${esc(c.about)}</p><div class="tags">${c.specialties.map(x=>`<span>${esc(x)}</span>`).join('')}</div>${c.links.map(([label,url])=>`<p><a href="${esc(url)}">${esc(label)} ↗</a></p>`).join('')}${record(c.name+' · Company')}</section><section aria-label="Company updates"><div class="section-head"><h2>Company updates</h2><span class="meta">Work, people & everyday life</span></div>${c.updates.map(post=>companyPostCard(id,post)).join('')}</section>${contributors.length?`<section class="card"><h2>Community conversation</h2>${contributors.map(([pid,text])=>`<div class="comment"><a href="#/person/${pid}">${avatar(pid)}</a><p><a href="#/person/${pid}">${esc(people[pid].name)}</a><br>${esc(text)}</p></div>`).join('')}${record(c.name+' · Conversation')}</section>`:''}${c.docs.length?`<section class="card"><h2>From the archive</h2>${c.docs.map(id=>`<div class="history"><a href="#/document/${id}">${esc(docs[id].title)}</a><p class="meta">${esc(docs[id].date)}</p></div>`).join('')}</section>`:''}</div><aside class="sidebar"><section class="card"><h2>People at ${esc(c.name)}</h2>${employees.length?employees.map(mini).join(''):'<p class="meta">Our team shares news and community projects in the company updates.</p>'}${former.length?`<h2 style="margin-top:24px">Past and present connections</h2>${former.map(mini).join('')}`:''}${c.partners?.length?`<h2 style="margin-top:24px">Around our community</h2>${c.partners.map(partner=>`<p>${companyLink(partner)}</p>`).join('')}`:''}<p><a class="meta" href="#/companies">Explore organizations →</a></p></section></aside></div>`;
}
function directory(type,q=''){
  const data=type==='people'?people:companies,words=q.toLowerCase().trim().split(/\s+/).filter(Boolean),matches=Object.entries(data).filter(([,p])=>words.every(w=>JSON.stringify(p).toLowerCase().includes(w)));
  main.innerHTML=`<div class="section-head"><h1>${type==='people'?'People':'Companies'}</h1><span class="meta">${matches.length} results${q?' for “'+esc(q)+'”':''}</span></div>${type==='companies'?'<p class="directory-intro">The teams behind the work, from neighborhood workshops to organizations across the region.</p>':''}<div class="people-grid">${matches.map(([id,p])=>`<article class="card">${type==='people'?avatar(id):`<a href="#/company/${id}" tabindex="-1" aria-hidden="true">${picture(p.image,'','company-thumbnail')}</a>`}<h2><a href="#/${type==='people'?'person':'company'}/${id}">${esc(p.name)}</a></h2><p>${esc(p.headline||p.tag)}</p><p class="meta">${esc(p.location)}</p>${type==='people'?companyLink(p.company):`<p class="meta">${esc(p.sector)} · ${p.updates.length} updates</p>`}</article>`).join('')}</div>${matches.length?'':'<p class="empty">No matches. Try another name or a broader topic.</p>'}`;
}
function search(q){
  const words=q.toLowerCase().trim().split(/\s+/).filter(Boolean),match=x=>words.every(w=>JSON.stringify(x).toLowerCase().includes(w)),results=[];
  for(const[id,p]of Object.entries(people)){if(match({name:p.name,headline:p.headline,bio:p.bio,skills:p.skills}))results.push([p.name,'/person/'+id,p.headline]);for(const post of p.posts)if(match(post))results.push([p.name+' · '+post.date,'/post/'+post.id,post.text]);}
  for(const[id,c]of Object.entries(companies)){if(match({name:c.name,tag:c.tag,about:c.about,location:c.location,sector:c.sector,specialties:c.specialties}))results.push([c.name,'/company/'+id,c.tag]);for(const post of c.updates)if(match(post))results.push([c.name+' · '+(post.title||post.date),'/company-post/'+post.id,post.text]);}
  for(const[id,d]of Object.entries(docs))if(match(d))results.push([d.title,'/document/'+id,d.date]);
  main.innerHTML=`<h1>Search results</h1><p class="muted">${results.length} matches for “${esc(q)}”</p>${results.map(([title,route,text])=>`<article class="card"><h2><a href="#${route}">${esc(title)}</a></h2><p>${esc(text)}</p></article>`).join('')||'<p class="empty">Try a name, company, skill, or topic.</p>'}`;
}
function documentPage(id){if(!own(docs,id))return missing();const d=docs[id];main.innerHTML=`<article class="article card"><p class="eyebrow">${companyLink(d.company)} · Archive</p><h1>${esc(d.title)}</h1><p class="meta">${esc(d.date)}</p>${d.sections.map(([title,text])=>`<section><h2>${esc(title)}</h2><p>${esc(text)}</p></section>`).join('')}<h2>People in this story</h2>${d.people.map(mini).join('')}${record(d.title)}</article>`;}
function postPage(id){for(const[owner,p]of Object.entries(people)){const found=p.posts.find(x=>x.id===id);if(found){main.innerHTML=`<div class="layout"><section><p><a href="#/person/${owner}">← ${esc(p.name)}’s profile</a></p>${postCard(owner,found)}</section>${sidebar(p.connections.slice(0,4))}</div>`;return;}}missing();}
function assignment(){main.innerHTML=`<section class="task-hero"><p class="eyebrow">MrQ OSINT Lab · Professional investigation</p><h1>An opportunity that sounds right.</h1><p>Act as a fictional recruiter offering a professional a tempting opportunity. Investigate their public footprint, then use AI to draft a simulated phishing email and examine what makes it convincing.</p><a class="button" href="#/people">Explore LinkedUP</a> <button class="secondary" id="assignment-notebook">Open research notebook ↗</button></section><section class="card"><h2>1 · Find connections and plan an opportunity</h2><p>Explore profiles, older posts, companies, and conversations. Use <strong>Record finding</strong> to send sources to one reusable notebook tab. Star the details you will use, then connect those details into an original recruitment opportunity.</p><h2>2 · Prompt AI and examine its email</h2><p>Write your prompt in the notebook and copy it with your plan and starred evidence into your teacher-approved AI tool. Paste the response back, keeping the invented sender, subject, and fake link together. Highlight telling phrases and explain how they might influence this person.</p><p>Use a professional tone and consider familiarity, authority, or urgency. Include visible link text and an invented .example destination. This is a fictional classroom draft for analysis.</p><h2>3 · Make a judgment</h2><p>Reflect on what you would change or check and why. Consider the AI’s assumptions, the quality of its persuasion, and how someone could verify the opportunity independently. Your starred findings appear in the report automatically.</p><p class="meta">The Casey investigation supports Unit 1.3–1.5; this activity connects to Unit 1.6–1.9. The end-of-unit PSA is a separate Canvas assignment.</p></section>`;$('#assignment-notebook').onclick=openNotebookTab;}
function login(){if(account){location.hash='/account';return;}main.innerHTML=`<section class="login-card"><a class="wordmark" href="#/feed">Linked<span>UP</span></a><h1>Sign in</h1><p>Stay connected to your professional world.</p><form id="login-form" autocomplete="off"><label for="login-email">Email</label><input id="login-email" type="email" required autocomplete="off"><label for="login-password">Password</label><input id="login-password" type="password" required autocomplete="off"><p id="login-error" class="error" role="status"></p><button type="submit">Sign in</button></form><p class="field-note"><a href="#/feed">Browse LinkedUP</a></p></section>`;$('#login-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button'),address=$('#login-email').value.trim().toLowerCase(),value=$('#login-password').value;$('#login-password').value='';button.disabled=true;$('#login-error').textContent='';try{account=await resolveWorkspace(address,value);if(account)location.hash='/account';else $('#login-error').textContent='That email and password combination was not recognized.';}catch{$('#login-error').textContent='Sign in is temporarily unavailable. Please try again.';}finally{button.disabled=false;}};}
async function resolveWorkspace(address,value){if(!crypto.subtle)throw Error('Unavailable');const decode=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(address+'\0'+value),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:decode(PROFILE_CACHE.palette),iterations:PROFILE_CACHE.rounds,hash:'SHA-256'},material,256);const fingerprint=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bits)),x=>x.toString(16).padStart(2,'0')).join('');if(fingerprint!==PROFILE_CACHE.signature)return null;const key=await crypto.subtle.importKey('raw',bits,'AES-GCM',false,['decrypt']);try{return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(PROFILE_CACHE.frame)},key,decode(PROFILE_CACHE.tiles))));}catch{return null;}}
function accountPage(view){if(!account){location.hash='/login';return;}const p=people[account.id];const menu=`<section class="card"><div class="post-author">${avatar(account.id)}<div><h1>${esc(p.name)}</h1><p>${esc(p.headline)}</p></div></div><div class="toolbar"><a class="button secondary" href="#/account">Home</a><a class="button secondary" href="#/messages">Messages</a><a class="button secondary" href="#/settings">Settings</a><button id="sign-out" class="secondary">Sign out</button></div></section>`;let content='';if(view==='messages'){content=`<section class="card"><h2>Messages</h2>${account.messages.map(m=>`<details class="disclosure"><summary>${esc(m.from)} · ${esc(m.subject)}</summary>${m.thread.map(([name,date,text])=>`<div class="inbox-message"><strong>${esc(name)}</strong><p class="meta">${esc(date)}</p><p>${esc(text)}</p></div>`).join('')}</details>`).join('')}</section>`;}else if(view==='settings'){content=`<section class="card"><h2>Account settings</h2>${[['Name',p.name],['Email',account.email],['Profile visibility','Public'],['Message notifications','Weekly digest'],['Location',p.location],['Language','English']].map(([k,v])=>`<div class="settings-row"><strong>${esc(k)}</strong><span>${esc(v)}</span></div>`).join('')}</section>`;}else{content=`<section class="card"><h2>Share an update</h2><textarea class="composer" aria-label="Start a post" placeholder="What would you like to share?" disabled></textarea><p class="meta">Publishing is unavailable in this view.</p><button disabled>Post</button></section><section class="card"><h2>Welcome back, ${esc(p.name.split(' ')[0])}</h2><p>You have ${account.messages.length} recent conversations.</p><a href="#/messages">Open messages →</a></section>${postCard(account.id,p.posts[0])}`;}main.innerHTML=`<div class="layout"><div>${menu}${content}</div>${sidebar(p.connections.slice(0,4))}</div>`;$('#sign-out').onclick=()=>{account=null;location.hash='/feed';};}
function missing(){main.innerHTML='<section class="card"><h1>Page not found</h1><a href="#/feed">Return to LinkedUP</a></section>';}
function wire(){main.querySelectorAll('[data-record]').forEach(button=>button.onclick=()=>sendFindingSource(button));main.querySelectorAll('[data-photo]').forEach(button=>button.onclick=()=>{const viewer=$('#photo-viewer');viewer.querySelector('img').src=imagePath(button.dataset.photo);viewer.querySelector('img').alt=button.dataset.photoAlt;$('#photo-caption').textContent=button.dataset.photoAlt;viewer.showModal();});}
$('#close-photo').onclick=()=>$('#photo-viewer').close();
$('#photo-viewer').addEventListener('click',event=>{if(event.target!==event.currentTarget)return;const bounds=event.currentTarget.getBoundingClientRect();if(event.clientX<bounds.left||event.clientX>bounds.right||event.clientY<bounds.top||event.clientY>bounds.bottom)event.currentTarget.close();});
function render(){const hash=location.hash.slice(1)||'/feed';const [path,query='']=hash.split('?'),[,view,id]=path.split('/'),q=new URLSearchParams(query).get('q')||'';switch(view){case'feed':feed();break;case'person':profile(id);break;case'people':directory('people',q);break;case'companies':directory('companies',q);break;case'company':company(id);break;case'post':postPage(id);break;case'company-post':companyUpdatePage(id);break;case'document':documentPage(id);break;case'search':search(q);break;case'assignment':assignment();break;case'notebook':notebook();break;case'report':report();break;case'login':login();break;case'account':case'messages':case'settings':accountPage(view);break;default:missing();}wire();syncNotebookRole();$('#session-link').textContent=account?'Me':'Sign in';$('#session-link').href=account?'#/account':'#/login';document.title=(main.querySelector('h1')?.textContent||'Your professional community')+' · LinkedUP';window.scrollTo(0,0);main.focus({preventScroll:true});}
$('#global-search').onsubmit=e=>{e.preventDefault();const q=$('#query').value.trim();if(q)location.hash='/search?q='+encodeURIComponent(q);};$('.skip').onclick=e=>{e.preventDefault();main.focus();};initNotebook();addEventListener('hashchange',render);render();
