/* All people, organizations, posts, and contact details here are fictional classroom content. */
const PROFILES = {
 casey:{name:'Casey Selvin',handle:'casey_thunder13',image:'casey',bio:'Riverdale Thunder #7 ⚽ · games after homework 🎮 · Lexington, KY',stats:'412 followers · 618 following',posts:['p101','p102','p103','p104','p105','p106']},
 dana:{name:'Dana Selvin',handle:'dana.selvin',image:'cafe',bio:'Coffee, books, and the occasional sideline. Community matters.',stats:'186 followers · 243 following',posts:['p201','p202','p203','p204']},
 thunder:{name:'Riverdale Thunder',handle:'riverdale_thunder',image:'field',bio:'Youth soccer in Lexington. Club updates and community photos.',stats:'1,208 followers · 93 following',posts:['p301','p302']},
 other:{name:'Casey Selvin',handle:'casey_draws',image:null,bio:'Columbus, OH · 17 · sketchbooks & ceramics',stats:'95 followers · 122 following',posts:['p401']},
 coach:{name:'Coach K',handle:'thunder.coach.k',image:'field',bio:'Riverdale Thunder coaching team. Club announcements live on our website.',stats:'204 followers · 88 following',posts:['p501']}
};
const POSTS = {
 p101:{owner:'casey',date:'24 Oct 2026 · 16:20',images:['family'],text:'Community Cup done! Thanks for showing up even in the cold. Best sideline crew 💙',comments:[['dana','Proud of you, kiddo. Your brother Eli ate two cupcakes before kickoff.'],['coach','Great teamwork today, number 7!']]},
 p102:{owner:'casey',date:'24 Oct 2026 · 13:05',images:['volunteers','cupcake'],text:'The snack table deserved its own post. Swipe for the important part 🧁 #ThunderCommunityCup',comments:[['dana','That is your third cupcake, Casey 😂'],['thunder','Thank you to everyone who volunteered! Recap is on the club site.']]},
 p103:{owner:'casey',date:'22 Oct 2026 · 19:15',images:['gaming'],text:'Homework finished. Finally time to build something that is not a slide presentation.',comments:[['thunder','Good luck Saturday!']]},
 p104:{owner:'casey',date:'18 Oct 2026 · 17:40',images:[],text:'Ok so I accidentally spent ALL my Robux on this skin 😭 Mom is NOT going to be happy. At least my username fits rn... Casey_Thunder13 stays winning 😂 #Roblox #RobuxProblems #Oops',comments:[['dana','We agreed on a budget. No more purchases this month.']]},
 p105:{owner:'casey',date:'10 Oct 2026 · 15:30',images:['casey'],text:'Number 7 reporting for duty. Riverdale MS colors forever. ⚽',comments:[['coach','See the club schedule for the Community Cup details.']]},
 p106:{owner:'casey',date:'14 Sep 2024 · 16:10',images:['soccer-selfie'],text:'Found this old photo from practice. Different field, same team energy.',comments:[]},
 p201:{owner:'dana',date:'25 Oct 2026 · 09:10',images:['cafe'],text:'A quiet coffee after a very loud Saturday. Now to sort the volunteer receipts before Monday. Club email is easiest while I am at work.',comments:[['thunder','Thanks, Dana! The organizer update has the details.']]},
 p202:{owner:'dana',date:'23 Oct 2026 · 20:35',images:['baking'],text:'Casey and I may have overcommitted on cupcakes. Blue icing everywhere. See you at the Community Cup tomorrow!',comments:[['casey','Quality control is a full time job.']]},
 p203:{owner:'dana',date:'01 Oct 2026 · 12:10',images:['dana-work'],text:'New staff photo day at Cedar & Finch. Grateful for a team that makes room for community volunteering.',comments:[]},
 p204:{owner:'dana',date:'15 Aug 2026 · 18:45',images:[],text:'Finished my library book exactly one day before it was due. Calling that a win.',comments:[]},
 p301:{owner:'thunder',date:'24 Oct 2026 · 18:00',images:['volunteers','cupcake'],text:'A community effort from start to finish. Thank you to Dana Selvin, our volunteer coordinator, and every family who joined the Thunder Community Cup. Full recap and original photo download on our club website.',comments:[['casey','Best day!'],['coach','Thanks @casey_thunder13 for helping at check-in before the match.']]},
 p302:{owner:'thunder',date:'12 Oct 2026 · 11:00',images:['field'],text:'Reminder: this year’s Community Cup is at Riverdale Park, Field 3. An old flyer is still being shared. Please use the current club announcement.',comments:[['dana','Volunteer signup questions? The organizer page has my club contact.']]},
 p401:{owner:'other',date:'20 Oct 2026 · 14:10',images:[],text:'Columbus art walk this weekend. Bringing my sketchbook and hoping it stays dry. Senior year is moving too fast.',comments:[]},
 p501:{owner:'coach',date:'20 Oct 2026 · 18:00',images:['field'],text:'Community Cup families: all official schedule changes go on the Riverdale Thunder club site. Please check there before forwarding a message.',comments:[]}
};
const ARTICLES = {
 'club-home':{service:'club',title:'Community soccer. Shared purpose.',date:'Riverdale Thunder · Lexington, Kentucky',image:'field',body:`<p>Welcome to the Riverdale Thunder youth soccer club. Find team news, event information, and community updates here.</p><h2>Latest from the club</h2><ul><li><a href="#/article/recap">Community Cup: thank you, Lexington</a> — 24 October 2026</li><li><a href="#/article/organizer">Volunteer follow-up and receipt deadline</a> — 25 October 2026</li><li><a href="#/article/current">2026 Community Cup announcement</a> — 12 October 2026</li><li><a href="#/article/roster">Riverdale MS team spotlight</a> — 5 October 2026</li></ul><p>Find us on <a href="#/profile/thunder">Frame @riverdale_thunder</a>.</p>`},
 roster:{service:'club',title:'Riverdale MS team spotlight',date:'5 October 2026 · Club news',image:'casey',body:`<p>Meet Casey M. Selvin, 13, a Riverdale Middle School student and number 7 for the Riverdale Thunder in Lexington.</p><p>Casey helped welcome new players at our fall practice. Her favorite part of the game? “When everyone gets involved.”</p><p>More team photos: <a href="#/profile/thunder">@riverdale_thunder on Frame</a>. Casey appears in our recent comments as <a href="#/social">@casey_thunder13</a>.</p>`},
 current:{service:'club',title:'2026 Thunder Community Cup',date:'12 October 2026 · Current announcement',image:'field',body:`<p><strong>Saturday, 24 October 2026 · 10:00–14:00</strong><br>Riverdale Park Soccer Complex, Field 3 · Lexington</p><p>A day of youth soccer, community stalls, and fundraising for team equipment.</p><p><strong>Venue update:</strong> Millcreek Park was our 2025 venue. This year’s event is at Riverdale Park. Please check the year on any flyer you receive.</p><p>Volunteer coordinator: <a href="#/article/organizer">Dana Selvin</a>. Community supporter: <a href="#/article/sponsor">Cedar & Finch Design</a>.</p><p>The event has now concluded. Read the <a href="#/article/recap">24 October recap</a>.</p>`},
 organizer:{service:'club',title:'Volunteer follow-up',date:'25 October 2026 · Organizer update',body:`<p>Thank you to all Community Cup volunteers. Dana Selvin is coordinating the final supply receipts.</p><p><strong>Outstanding task:</strong> send receipts for approved event supplies by <strong>Monday, 26 October, at 17:00</strong>. Dana will reconcile them with the club treasurer.</p><p>Contact: <strong>dana.selvin@thunder.example</strong>. Email is preferred during Dana’s workday. This address is a fictional training address.</p><p>Our volunteers included parents, coaches, and colleagues from <a href="#/article/sponsor">Cedar & Finch Design</a>. Dana’s daughter Casey played in the event.</p><p>Changes to this process will appear on this club page. A familiar name in an unexpected message is not sufficient confirmation.</p>`},
 recap:{service:'club',title:'Community Cup: thank you, Lexington',date:'24 October 2026 · 18:30 · Club news',image:'volunteers',body:`<p>Riverdale Park’s Field 3 was busy from the first whistle to the final cupcake. Thank you to Dana Selvin, our volunteer coordinator, and the families who made today possible.</p><p>Casey Selvin, number 7, helped at the welcome table before joining her team. Coach K and the club volunteers kept the day moving.</p><p>Community supporter <a href="#/article/sponsor">Cedar & Finch Design</a> provided printed event materials.</p><h2>Photo desk</h2><p>Want the photographer’s original rather than the resized web image?</p><p><a href="assets/DSC_1042.jpg" download="DSC_1042.jpg">Download original photo · DSC_1042.jpg</a></p><p class="small muted">Classroom file. Use the File inspector in your workspace to examine the downloaded file.</p><p><a href="#/article/organizer">Volunteer follow-up and receipt deadline</a></p>`},
 archive:{service:'club',title:'Club archive',date:'Past seasons and announcements',body:`<p>Browse older club material. Dates matter: these pages remain available as a historical record.</p><ul><li><a href="#/article/old">2025 Community Cup flyer</a></li><li><a href="#/article/current">2026 Community Cup announcement</a></li><li><a href="#/article/roster">October 2026 team spotlight</a></li></ul>`},
 old:{service:'club',title:'2025 Thunder Community Cup',date:'Archived · Published 10 October 2025',body:`<p><strong>Saturday, 25 October 2025</strong><br>Millcreek Park, Field B · Lexington</p><p>Join families and friends for soccer and a community bake sale. Dana Selvin will help with volunteer check-in.</p><p>This page documents the 2025 event. For the 2026 venue, see <a href="#/article/current">the current announcement</a>.</p>`},
 'work-home':{service:'work',title:'Design that brings people together.',date:'Cedar & Finch Design · Lexington studio',image:'dana-work',body:`<p>We are a fictional community-focused design studio creating print and digital materials for local organizations.</p><h2>People and projects</h2><ul><li><a href="#/article/dana-bio">Meet Dana Selvin, project coordinator</a></li><li><a href="#/article/sponsor">Supporting the Thunder Community Cup</a></li></ul><p>Studio notes, project stories, and our team’s work in the community.</p>`},
 'dana-bio':{service:'work',title:'Dana Selvin',date:'Project coordinator · Staff biography · Updated 1 October 2026',image:'dana-work',body:`<p>Dana coordinates project schedules and supplier communication at Cedar & Finch Design in Lexington. She joined the studio in 2022 after working in Louisville.</p><p>Outside the studio, Dana volunteers with Riverdale Thunder youth soccer. She enjoys library books, coffee, and cheering on her children.</p><p>Work contact: <strong>dana.selvin@cedarfinch.example</strong> (fictional training address).</p><p>Read about our <a href="#/article/sponsor">Community Cup support</a>.</p>`},
 sponsor:{service:'work',title:'A small contribution to a big community day',date:'24 October 2026 · 19:00 · Studio journal',image:'baking',body:`<p>Cedar & Finch Design supported this year’s Thunder Community Cup with printed signage and volunteer time.</p><p>Our project coordinator <a href="#/article/dana-bio">Dana Selvin</a> is also the club’s volunteer coordinator. Her daughter Casey plays for Riverdale Thunder.</p><p>Dana’s family contributed blue-and-white cupcakes, too. We are grateful to everyone helping with the event.</p><p>Event details and volunteer questions belong on the <a href="#/article/current">Riverdale Thunder club website</a>.</p>`},
 'casey-ohio':{service:'directory',title:'Casey Selvin · Columbus',date:'Public profile summary · Updated September 2026',body:`<p>Casey B. Selvin, 17, Columbus, Ohio. Interests: ceramics and illustration. Public username: <a href="#/profile/other">casey_draws</a>.</p><p>This summary may be incomplete. Verify identity using independent sources.</p>`},
 'dana-other':{service:'directory',title:'Dana Selvin · Portland',date:'Community contributor directory',body:`<p>Dana R. Selvin is a landscape photographer based in Portland, Oregon. Her published work focuses on the Pacific Northwest.</p><p>No Lexington employer or Riverdale club affiliation is listed.</p>`}
};
const SEARCH_INDEX = [
 {title:'Frame · find your people',route:'/social',site:'frame.training',text:'Search public profiles, photos, and community posts.',keys:'casey selvin dana social username frame'},
 {title:'Riverdale MS team spotlight',route:'/article/roster',site:'thunder.training / news / team-spotlight',text:'A Lexington youth soccer player helps welcome the next season.',keys:'casey selvin lexington riverdale thunder school soccer jersey 7'},
 {title:'Casey Selvin · Columbus artist',route:'/article/casey-ohio',site:'people.training / casey-selvin',text:'Illustration, ceramics, and the Columbus art walk.',keys:'casey selvin ohio columbus'},
 {title:'PlaySpace · community search',route:'/gaming',site:'playspace.training',text:'Find public player profiles by their handle.',keys:'casey_thunder13 casey thunder13 gaming roblox playspace'},
 {title:'2025 Thunder Community Cup',route:'/article/old',site:'thunder.training / archive / 2025',text:'Archived flyer: Millcreek Park, Field B. Published October 2025.',keys:'thunder community cup venue millcreek fundraiser dana selvin'},
 {title:'2026 Thunder Community Cup',route:'/article/current',site:'thunder.training / events / 2026',text:'Current event announcement and venue update.',keys:'thunder community cup riverdale park venue fundraiser date 2026'},
 {title:'Dana Selvin · Cedar & Finch Design',route:'/article/dana-bio',site:'cedarfinch.training / people / dana-selvin',text:'Meet our Lexington project coordinator.',keys:'dana selvin cedar finch employer work lexington louisville'},
 {title:'Dana Selvin · Portland photography',route:'/article/dana-other',site:'directory.training / contributors',text:'Landscape photography from the Pacific Northwest.',keys:'dana selvin portland'},
 {title:'Volunteer follow-up',route:'/article/organizer',site:'thunder.training / volunteers / follow-up',text:'Supply receipts and the coordinator’s preferred contact channel.',keys:'dana selvin thunder community cup volunteer receipts deadline email coordinator'},
 {title:'Community Cup: thank you, Lexington',route:'/article/recap',site:'thunder.training / news / cup-recap',text:'A day at Field 3. Event recap and original photo download.',keys:'thunder community cup recap photo original download dana selvin casey'},
 {title:'Supporting the Thunder Community Cup',route:'/article/sponsor',site:'cedarfinch.training / journal / community',text:'Print materials, volunteer time, and a family contribution.',keys:'cedar finch thunder sponsor community cup dana selvin'},
 {title:'Riverdale Thunder · archive',route:'/article/archive',site:'thunder.training / archive',text:'Past seasons and event announcements.',keys:'thunder riverdale archive old flyer'}
];
