/* All people, organizations, posts, and contact details here are fictional classroom content. */
const PROFILES = {
 casey:{name:'Casey Selvin',handle:'casey_thunder13',image:'casey',bio:'Riverdale Thunder #7 ⚽ · games after homework 🎮 · Lexington, KY',stats:'412 followers · 618 following',posts:['p101','p102','p103','p104','p105','p106']},
 dana:{name:'Dana Selvin',handle:'dana.selvin',image:'cafe',bio:'Coffee, books, and the occasional sideline. Community matters.',stats:'186 followers · 243 following',posts:['p201','p202','p203','p204']},
 thunder:{name:'Riverdale Thunder',handle:'riverdale_thunder',image:'field',bio:'Youth soccer in Lexington. Club updates and community photos.',stats:'1,208 followers · 93 following',posts:['p301','p302']},
 other:{name:'Casey Selvin',handle:'casey_draws',image:'casey-artist',bio:'Columbus, OH · 17 · sketchbooks & ceramics',stats:'95 followers · 122 following',posts:['p401']},
 coach:{name:'Coach K',handle:'thunder.coach.k',image:'coach-kai',bio:'Riverdale Thunder coaching team. Club announcements live on our website.',stats:'204 followers · 88 following',posts:['p501']}
};
const POSTS = {
 p101:{owner:'casey',date:'24 Oct 2026 · 16:20',images:['family'],text:'Community Cup done! Thanks for showing up even in the cold. Best sideline crew 💙',comments:[['dana','Proud of you, kiddo. Your brother Eli ate two cupcakes before kickoff.'],['coach','Great teamwork today, number 7!']]},
 p102:{owner:'casey',date:'24 Oct 2026 · 13:05',images:['volunteers','cupcake'],text:'The snack table deserved its own post. Swipe for the important part 🧁 #ThunderCommunityCup',comments:[['dana','That is your third cupcake, Casey 😂'],['thunder','Thank you to everyone who volunteered! Recap is on the club site.']]},
 p103:{owner:'casey',date:'22 Oct 2026 · 19:15',images:['gaming'],text:'Homework finished. Finally time to build something that is not a slide presentation.',comments:[['thunder','Good luck Saturday!']]},
 p104:{owner:'casey',date:'18 Oct 2026 · 17:40',images:[],text:'Ok so I accidentally spent ALL my Robux on this skin 😭 Mom is NOT going to be happy. At least my username fits rn... Casey_Thunder13 stays winning 😂 #Roblox #RobuxProblems #Oops',comments:[['dana','We agreed on a budget. No more purchases this month.']]},
 p105:{owner:'casey',date:'10 Oct 2026 · 15:30',images:['casey'],text:'Number 7 reporting for duty. Riverdale MS colors forever. ⚽',comments:[['coach','See the club schedule for the Community Cup details.']]},
 p106:{owner:'casey',date:'14 Sep 2024 · 16:10',images:['soccer-selfie'],text:'Found this old photo from practice. Different field, same team energy.',comments:[]},
 p201:{owner:'dana',date:'25 Oct 2026 · 09:10',images:['cafe'],text:'A quiet coffee after a very loud Saturday. Now to sort the volunteer receipts before Monday. Club email is easiest while I am at work.',comments:[['thunder','Thanks, Dana! The organizer update has the details.']]},
 p202:{owner:'dana',date:'23 Oct 2026 · 20:35',images:['baking'],text:'Casey and I may have overcommitted on cupcakes. Blue icing everywhere. See you at the Community Cup tomorrow!',comments:[['casey','Quality control is a full time job.']]},
 p203:{owner:'dana',date:'01 Oct 2026 · 12:10',images:['dana-work'],text:'New staff photo day at Cedar & Finch. Grateful for a team that makes room for community volunteering.',comments:[]},
 p204:{owner:'dana',date:'15 Aug 2026 · 18:45',images:[],text:'Finished my library book exactly one day before it was due. Calling that a win.',comments:[]},
 p301:{owner:'thunder',date:'24 Oct 2026 · 18:00',images:['volunteers','cupcake'],text:'A community effort from start to finish. Thank you to Dana Selvin, our volunteer coordinator, and every family who joined the Thunder Community Cup. Full recap and match photos on our club website.',comments:[['casey','Best day!'],['coach','Thanks @casey_thunder13 for helping at check-in before the match.']]},
 p302:{owner:'thunder',date:'12 Oct 2026 · 11:00',images:['field'],text:'Reminder: this year’s Community Cup is at Riverdale Park, Field 3. An old flyer is still being shared. Please use the current club announcement.',comments:[['dana','Volunteer signup questions? The organizer page has my club contact.']]},
 p401:{owner:'other',date:'20 Oct 2026 · 14:10',images:['casey-artist'],text:'Columbus art walk setup: sketchbooks, little ceramic bowls, and fingers crossed for dry weather. Senior year is moving too fast.',comments:[]},
 p501:{owner:'coach',date:'20 Oct 2026 · 18:00',images:['field'],text:'Community Cup families: all official schedule changes go on the Riverdale Thunder club site. Please check there before forwarding a message.',comments:[]}
};
const ARTICLES = {
 'club-home':{service:'club',title:'Community soccer. Shared purpose.',date:'Riverdale Thunder · Lexington, Kentucky',image:'field',body:`<p>Welcome to the Riverdale Thunder youth soccer club. Find team news, event information, and community updates here.</p><h2>Latest from the club</h2><ul><li><a href="#/article/recap">Community Cup: thank you, Lexington</a> — 24 October 2026</li><li><a href="#/article/organizer">Volunteer follow-up and receipt deadline</a> — 25 October 2026</li><li><a href="#/article/current">2026 Community Cup announcement</a> — 12 October 2026</li><li><a href="#/article/roster">Riverdale MS team spotlight</a> — 5 October 2026</li></ul><p>Find us on <a href="#/profile/thunder">Frame @riverdale_thunder</a>.</p>`},
 roster:{service:'club',title:'Riverdale MS team spotlight',date:'5 October 2026 · Club news',image:'casey',body:`<p>Meet Casey M. Selvin, 13, a Riverdale Middle School student and number 7 for the Riverdale Thunder in Lexington.</p><p>Casey helped welcome new players at our fall practice. Her favorite part of the game? “When everyone gets involved.”</p><p>More team photos: <a href="#/profile/thunder">@riverdale_thunder on Frame</a>. Casey appears in our recent comments as <a href="#/social">@casey_thunder13</a>.</p>`},
 current:{service:'club',title:'2026 Thunder Community Cup',date:'12 October 2026 · Current announcement',image:'field',body:`<p><strong>Saturday, 24 October 2026 · 10:00–14:00</strong><br>Riverdale Park Soccer Complex, Field 3 · Lexington</p><p>A day of youth soccer, community stalls, and fundraising for team equipment.</p><p><strong>Venue update:</strong> Millcreek Park was our 2025 venue. This year’s event is at Riverdale Park. Please check the year on any flyer you receive.</p><p>Volunteer coordinator: <a href="#/article/organizer">Dana Selvin</a>. Community supporter: <a href="#/article/sponsor">Cedar & Finch Design</a>.</p><p>The event has now concluded. Read the <a href="#/article/recap">24 October recap</a>.</p>`},
 organizer:{service:'club',title:'Volunteer follow-up',date:'25 October 2026 · Organizer update',body:`<p>Thank you to all Community Cup volunteers. Dana Selvin is coordinating the final supply receipts.</p><p><strong>Outstanding task:</strong> send receipts for approved event supplies by <strong>Monday, 26 October, at 17:00</strong>. Dana will reconcile them with the club treasurer.</p><p>Contact: <strong>dana.selvin@thunder.example</strong>. Email is preferred during Dana’s workday. This address is a fictional training address.</p><p>Our volunteers included parents, coaches, and colleagues from <a href="#/article/sponsor">Cedar & Finch Design</a>. Dana’s daughter Casey played in the event.</p><p>Changes to this process will appear on this club page. A familiar name in an unexpected message is not sufficient confirmation.</p>`},
 recap:{service:'club',title:'Community Cup: thank you, Lexington',date:'24 October 2026 · 18:30 · Club news',image:'DSC_1042',body:`<p>Riverdale Park’s Field 3 was busy from the first whistle to the final cupcake. Thank you to Dana Selvin, our volunteer coordinator, and the families who made today possible.</p><p>Casey Selvin, number 7, helped at the welcome table before joining her team. Coach K and the club volunteers kept the day moving.</p><p>Community supporter <a href="#/article/sponsor">Cedar & Finch Design</a> provided printed event materials.</p><p><a href="#/article/organizer">Volunteer follow-up and receipt deadline</a></p>`},
 archive:{service:'club',title:'Club archive',date:'Past seasons and announcements',body:`<p>Browse older club material. Dates matter: these pages remain available as a historical record.</p><ul><li><a href="#/article/old">2025 Community Cup flyer</a></li><li><a href="#/article/current">2026 Community Cup announcement</a></li><li><a href="#/article/roster">October 2026 team spotlight</a></li></ul>`},
 old:{service:'club',title:'2025 Thunder Community Cup',date:'Archived · Published 10 October 2025',body:`<p><strong>Saturday, 25 October 2025</strong><br>Millcreek Park, Field B · Lexington</p><p>Join families and friends for soccer and a community bake sale. Dana Selvin will help with volunteer check-in.</p><p>This page documents the 2025 event. For the 2026 venue, see <a href="#/article/current">the current announcement</a>.</p>`},
 'work-home':{service:'work',title:'Design that brings people together.',date:'Cedar & Finch Design · Lexington studio',image:'dana-work',body:`<p>We are a fictional community-focused design studio creating print and digital materials for local organizations.</p><h2>People and projects</h2><ul><li><a href="#/article/dana-bio">Meet Dana Selvin, project coordinator</a></li><li><a href="#/article/sponsor">Supporting the Thunder Community Cup</a></li></ul><p>Studio notes, project stories, and our team’s work in the community.</p>`},
 'dana-bio':{service:'work',title:'Dana Selvin',date:'Project coordinator · Staff biography · Updated 1 October 2026',image:'dana-work',body:`<p>Dana coordinates project schedules and supplier communication at Cedar & Finch Design in Lexington. She joined the studio in 2022 after working in Louisville.</p><p>Outside the studio, Dana volunteers with Riverdale Thunder youth soccer. She enjoys library books, coffee, and cheering on her children.</p><p>Work contact: <strong>dana.selvin@cedarfinch.example</strong> (fictional training address).</p><p>Read about our <a href="#/article/sponsor">Community Cup support</a>.</p>`},
 sponsor:{service:'work',title:'A small contribution to a big community day',date:'24 October 2026 · 19:00 · Studio journal',image:'baking',body:`<p>Cedar & Finch Design supported this year’s Thunder Community Cup with printed signage and volunteer time.</p><p>Our project coordinator <a href="#/article/dana-bio">Dana Selvin</a> is also the club’s volunteer coordinator. Her daughter Casey plays for Riverdale Thunder.</p><p>Dana’s family contributed blue-and-white cupcakes, too. We are grateful to everyone helping with the event.</p><p>Event details and volunteer questions belong on the <a href="#/article/current">Riverdale Thunder club website</a>.</p>`},
 'casey-ohio':{service:'directory',title:'Casey Selvin · Columbus',date:'Public profile summary · Updated September 2026',body:`<p>Casey B. Selvin, 17, Columbus, Ohio. Interests: ceramics and illustration. Public username: <a href="#/profile/other">casey_draws</a>.</p><p>This summary may be incomplete. Verify identity using independent sources.</p>`},
 'dana-other':{service:'directory',title:'Dana Selvin · Portland',date:'Community contributor directory',body:`<p>Dana R. Selvin is a landscape photographer based in Portland, Oregon. Her published work focuses on the Pacific Northwest.</p><p>No Lexington employer or Riverdale club affiliation is listed.</p>`}
};
const SEARCH_INDEX = [
 {title:'Frame · find your people',route:'/social',site:'frame.training',text:'Search public profiles, photos, and community posts.',keys:'casey selvin dana social username frame'},
 {title:'Riverdale MS team spotlight',route:'/article/roster',site:'thunder.training / news / team-spotlight',text:'A Lexington youth soccer player helps welcome the next season.',keys:'casey selvin lexington riverdale thunder school soccer jersey 7'},
 {title:'Casey Selvin · Columbus artist',route:'/article/casey-ohio',site:'people.training / casey-selvin',text:'Illustration, ceramics, and the Columbus art walk.',keys:'casey selvin ohio columbus'},
 {title:'PlaySpace · community search',route:'/gaming',site:'playspace.training',text:'Find public player profiles by their handle.',keys:'casey_thunder13 casey thunder13 gaming roblox playspace'},
 {title:'2025 Thunder Community Cup',route:'/article/old',site:'thunder.training / archive / 2025',text:'Archived flyer: Millcreek Park, Field B. Published October 2025.',keys:'thunder community cup venue millcreek fundraiser dana selvin'},
 {title:'2026 Thunder Community Cup',route:'/article/current',site:'thunder.training / events / 2026',text:'Current event announcement and venue update.',keys:'thunder community cup riverdale park venue fundraiser date 2026'},
 {title:'Dana Selvin · Cedar & Finch Design',route:'/article/dana-bio',site:'cedarfinch.training / people / dana-selvin',text:'Meet our Lexington project coordinator.',keys:'dana selvin cedar finch employer work lexington louisville'},
 {title:'Dana Selvin · Portland photography',route:'/article/dana-other',site:'directory.training / contributors',text:'Landscape photography from the Pacific Northwest.',keys:'dana selvin portland'},
 {title:'Volunteer follow-up',route:'/article/organizer',site:'thunder.training / volunteers / follow-up',text:'Supply receipts and the coordinator’s preferred contact channel.',keys:'dana selvin thunder community cup volunteer receipts deadline email coordinator'},
 {title:'Community Cup: thank you, Lexington',route:'/article/recap',site:'thunder.training / news / cup-recap',text:'A day at Field 3. Event recap and match photos.',keys:'thunder community cup recap photo dana selvin casey'},
 {title:'Supporting the Thunder Community Cup',route:'/article/sponsor',site:'cedarfinch.training / journal / community',text:'Print materials, volunteer time, and a family contribution.',keys:'cedar finch thunder sponsor community cup dana selvin'},
 {title:'Riverdale Thunder · archive',route:'/article/archive',site:'thunder.training / archive',text:'Past seasons and event announcements.',keys:'thunder riverdale archive old flyer'}
];

/* Expanded fictional community. The case remains frozen on 25 October 2026. */
Object.assign(PROFILES, {
 maya:{name:'Maya Torres',handle:'maya.makes',image:null,bio:'Riverdale MS · robotics, terrible puns, good playlists. Lexington. Art club on Thursdays.',stats:'231 followers · 307 following',posts:['m1','m2']},
 jordan:{name:'Jordan Lee',handle:'jordan.levels',image:null,bio:'8th grade · keyboards & co-op games · Lexington 🎮 BlueStorm32 in game.',stats:'178 followers · 260 following',posts:['j1','j2']},
 priya:{name:'Priya Shah',handle:'priya.onfilm',image:'priya-camera',bio:'Riverdale yearbook 📷 · photos, library books, and too many tabs.',stats:'305 followers · 284 following',posts:['pr1','pr2']},
 sportz:{name:'Avery Brooks',handle:'sportzgirl22',image:'avery-volleyball',bio:'Volleyball + soccer · Eastview Middle · Lexington. Usually at the library after school.',stats:'194 followers · 201 following',posts:['a1']},
 gamer:{name:'Noah Bennett',handle:'gamer_dude99',image:'noah-gaming',bio:'Louisville · game builds & baking experiments. Adopt Me collector.',stats:'89 followers · 170 following',posts:['n1']},
 stevens:{name:'Casey Stevens',handle:'casey.stevens',image:'casey-stage',bio:'Lexington · Lafayette theatre crew · stage paint is a permanent accessory.',stats:'382 followers · 490 following',posts:['cs1','cs2']},
 corey:{name:'Corey Selvin',handle:'corey.rides',image:'corey-shop',bio:'Bike mechanic at Spoke & Wrench · Lexington. Weekend rides, stubborn repairs, and good coffee.',stats:'614 followers · 388 following',posts:['co1','co2']},
 denver:{name:'Casey Selvin',handle:'casey.trails',image:'casey-denver',bio:'Denver, CO · landscape architect · trail maps and very early coffee.',stats:'522 followers · 342 following',posts:['de1']},
 lena:{name:'Lena Ortiz',handle:'lena.letters',image:'lena-print',bio:'Designer at Cedar & Finch · lettering, printmaking, Lexington walks.',stats:'402 followers · 506 following',posts:['l1']},
 sam:{name:'Sam Reed',handle:'sam.reed.design',image:'sam-garden',bio:'Cedar & Finch · digital design · board games, community gardens, Lexington.',stats:'213 followers · 339 following',posts:['s2','s1']},
 ellis:{name:'Ellis Morgan',handle:'ellis.reads',image:'ellis-library',bio:'Lexington library volunteer. Mystery novels and neighborhood history.',stats:'102 followers · 96 following',posts:['e1']}
});
PROFILES.casey.image='slide-casey';
PROFILES.casey.bio='Riverdale Thunder #7 ⚽ · Gamer @Casey_Thunder13 🎮 · music + STEM · Lexington, KY · Riverdale MS';
PROFILES.casey.links=[['TikTok · clips & chaos','/tiktok/casey'],['Twitch · Casey_Thunder','/twitch/casey']];
PROFILES.casey.posts=['p101','p107','p108','p102','p109','p103','p104','p105','p106'];
PROFILES.coach.name='Kai Morgan';PROFILES.coach.bio='Coach K · Riverdale Thunder · Lexington. Science teacher, trail runner, and dad-joke enthusiast. Saturday coffee at Juniper.';
PROFILES.coach.posts=['p501','k2'];
PROFILES.dana.bio='Books in every bag. Coffee before conversation. Mom to Casey & Eli. Lexington via Louisville.';
POSTS.p103.images=['roblox-avatar'];POSTS.p103.comments=[['jordan','The roof took us longer than the actual house.'],['maya','I still think the pink windows worked.'],['gamer','Brookhaven next?'],['casey','Maybe. I promised Eli he could pick tonight.'],['priya','Can someone please finish our real slides too 😭']];
POSTS.p104.images=['roblox-avatar'];POSTS.p104.comments=[['jordan','Blue lightning again 😂'],['sportz','Worth it for the screenshot'],['maya','Saving mine for the winter update'],['dana','We agreed on a budget. No more purchases this month.'],['gamer','Wait is this the same handle as on your clips?'],['casey','Yep lol. Twitch is Casey_Thunder though.'],['priya','The shoes are kind of great'],['jordan','I give the outfit 8/10, needs a hat']];
POSTS.p105.images=['slide-casey'];POSTS.p105.comments=[['sportz','That blue is so good'],['maya','You had that ball in every photo'],['coach','Good effort at training this week.'],['jordan','Strong profile picture energy']];
POSTS.p106.images=['slide-selfie'];
POSTS.p101.comments=[['priya','My camera battery barely made it'],['maya','Those cupcakes disappeared FAST'],['dana','Proud of you, kiddo. Your brother Eli ate two cupcakes before kickoff.'],['jordan','I was mostly there for snacks'],['sportz','Was this at the same place as last year?'],['casey','No, different park this time!'],['coach','Great teamwork today, number 7!'],['lena','Such a good turnout 💙']];
POSTS.p102.comments=[['maya','Slide two is the reason I came'],['priya','The blue frosting is still on my camera strap'],['dana','That is your third cupcake, Casey 😂'],['corey','Great day for being outside'],['thunder','Thank you to everyone who volunteered!'],['jordan','Who brought the lemon ones?']];
POSTS.p201.comments=[['ellis','Did you finish The Moonstone?'],['dana','Finally! Returned it this morning.'],['lena','Your mug is in the studio kitchen again'],['dana','Please save it for me 😂'],['thunder','Thanks for sorting everything yesterday.']];
Object.assign(POSTS, {
 p107:{owner:'casey',date:'23 Oct 2026 · 15:45',images:['school-friends'],text:'Science showcase survived. Maya built the sensor, Jordan fixed our slides, I supplied the playlist. Priya gets photo credit because she made us do this three times. #RiverdaleMS',comments:[['maya','The sensor only worked because you stopped touching it'],['jordan','Three font changes is not fixing the slides'],['priya','And this was still the least blurry one'],['sportz','What was the project?'],['maya','Soil moisture sensor for the garden club 🌱'],['casey','There was water everywhere'],['dana','Love seeing you all work together.'],['gamer','Can it water my virtual plants too']]},
 p108:{owner:'casey',date:'22 Oct 2026 · 20:50',images:['stream-avatar'],text:'New headset, same terrible aim. Saturday stream if I finish homework. Tomodachi Life has completely taken over my brain.',comments:[['jordan','BlueStorm32 reporting for snack duty'],['maya','The little island drama is better than TV'],['gamer','Roblox first?'],['casey','Probably. Then island time.'],['priya','Please turn the mic on this time'],['casey','That happened ONCE'],['sportz','The purple light looks cool']]},
 p109:{owner:'casey',date:'20 Oct 2026 · 17:05',images:['team-celebration'],text:'Still thinking about this win. Team group chat has not recovered. Maya and Priya found us after the match and we went for hot chocolate.',comments:[['priya','I took 42 photos and someone blinked in every one'],['maya','It was me'],['coach','Proud of the whole team.'],['sportz','Congrats!!'],['jordan','Hot chocolate was the right call']]},
 m1:{owner:'maya',date:'23 Oct 2026 · 17:30',images:['school-friends'],text:'We got the garden sensor working! Casey did the demo and Jordan rescued the laptop. Riverdale science showcase was loud but worth it.',comments:[['jordan','Next year we label the cables'],['casey','Next year we bring towels']]},
 m2:{owner:'maya',date:'18 Oct 2026 · 14:00',images:[],text:'Art club is collecting old magazines for Thursday collages. Drop them with Ms. Chen after lunch. Mine is becoming mostly pictures of plants.',comments:[['priya','I have a stack!']]},
 j1:{owner:'jordan',date:'22 Oct 2026 · 21:10',images:['roblox-avatar'],text:'Casey sent the new outfit reveal. Meanwhile BlueStorm32 is still wearing the free hat. Saving for a keyboard first.',comments:[['casey','Free hat is iconic'],['gamer','Which switches?'],['jordan','Quiet ones. My sister is tired of hearing me type.']]},
 j2:{owner:'jordan',date:'17 Oct 2026 · 15:20',images:[],text:'Yearbook photo retakes Monday at Riverdale. Reminder to myself to actually bring the form.',comments:[['priya','And to stop making faces at my camera']]},
 pr1:{owner:'priya',date:'24 Oct 2026 · 19:00',images:['team-celebration'],text:'One for the yearbook. Riverdale Thunder gave us plenty to photograph this month. More community photos in the Lexington Ledger.',comments:[['casey','The trophy almost fell'],['maya','Do not publish the blurry one']]},
 pr2:{owner:'priya',date:'16 Oct 2026 · 16:20',images:['sunset-clip'],text:'Waiting for Dad outside the library. The sky did all the work today.',comments:[['ellis','Lovely light!'],['maya','Album cover']]},
 a1:{owner:'sportz',date:'21 Oct 2026 · 17:00',images:['avery-volleyball'],text:'Eastview volleyball season done. Trying soccer with my cousin next. Library study group tomorrow before the weekend.',comments:[['casey','You will love it']]},
 n1:{owner:'gamer',date:'19 Oct 2026 · 20:30',images:['noah-gaming'],text:'Louisville rain means build night. Working on a bakery in Adopt Me. The cookies on the desk are Mom’s; I am still responsible for the virtual version.',comments:[['jordan','The irony']]},
 cs1:{owner:'stevens',date:'23 Oct 2026 · 18:10',images:['casey-stage'],text:'Lafayette fall play crew, we did it. I painted six doors and none of them open. Lexington friends: opening night is next Friday.',comments:[['corey','Break a leg!']]},
 cs2:{owner:'stevens',date:'15 Oct 2026 · 14:00',images:['studio-desk'],text:'Portfolio applications and theatre paint everywhere. Last year of high school is going quickly.',comments:[]},
 co1:{owner:'corey',date:'24 Oct 2026 · 10:30',images:['corey-shop'],text:'Busy Saturday at Spoke & Wrench. Two brake adjustments, a new inner tube, and one very stubborn bell. Glad we got the library bike back on the road before lunch.',comments:[['ellis','The library bike is rolling again. Thank you!']]},
 co2:{owner:'corey',date:'18 Oct 2026 · 08:00',images:['sunset-clip'],text:'Lexington loop before work. Thirty miles, one flat tire, excellent coffee at the end.',comments:[]},
 de1:{owner:'denver',date:'22 Oct 2026 · 08:00',images:['casey-denver'],text:'Denver studio review today. Still revising the trail planting plan. Forty-one and I still leave presentation boards until the last minute.',comments:[]},
 k2:{owner:'coach',date:'19 Oct 2026 · 07:20',images:['coach-kai'],text:'Early run before lesson planning. Kai Morgan on paper; Coach K if you are holding a soccer ball. Juniper coffee has become a Sunday habit.',comments:[['ellis','History walk next Sunday if you fancy a change'],['coach','As long as there is coffee afterward']]},
 l1:{owner:'lena',date:'21 Oct 2026 · 12:00',images:['lena-print'],text:'Color proofs everywhere at Cedar & Finch. Dana found the one typo we had all stopped seeing. Printmaking workshop at the arts center next month!',comments:[['sam','The kerning debate continues'],['dana','Someone has to read the dates']]},
 s1:{owner:'sam',date:'20 Oct 2026 · 18:00',images:['studio-desk'],text:'New portfolio layout nearly done. Swapping screens for the community garden this weekend. Lena gets naming rights if the tomatoes survive.',comments:[['lena','They are already named']]},
 e1:{owner:'ellis',date:'22 Oct 2026 · 10:00',images:['ellis-library'],text:'Neighborhood history walk starts at the library steps Sunday at 10. Bring comfortable shoes. I have finally found the old station photographs.',comments:[['corey','See you there']]}
});
const CLIPS=[
 {id:'practice',date:'15 Sep 2024',image:'soccer-clip',title:'⚽ me at practice today lol',views:'2,345',comments:[['sportz',"omg you’re so good!! what team do you play for??"],['casey','Riverdale Thunder ⚽ we have a game this Saturday at Springfield Park! come watch 😂'],['priya','The camera work is amazing. You are welcome.'],['gamer',"wait aren’t you Casey_Thunder13 on Roblox lol"],['casey','yes 😂 literally my account everywhere. I need a more creative username lol'],['maya','The ball disappearing at the end 😭'],['dana','Be home by 5:30 sweetie! Eli has his dentist appointment at 6 💕'],['casey',"MOM STOP COMMENTING ON MY VIDEOS 😭 yes okay I’ll be home"],['jordan','Soundtrack 10/10'],['coach','Great footwork Casey! Practice moved to 4pm Tuesday — Millcreek Field B.'],['sportz','Ty!!'],['maya','I watched this four times']]},
 {id:'cup',date:'24 Oct 2026',image:'team-celebration',title:'Cold hands, loud sidelines 💙 #CommunityCup',views:'4,879',comments:[['priya','My favorite photo from the set'],['jordan','Cupcake review when?'],['casey','Five stars, no notes'],['lena','Glad the signs survived the wind'],['dana','Thanks for helping at check-in before your match.'],['sportz','Different field from your old clip?'],['casey','Yep, Riverdale Park this year'],['maya','I need that group photo']]},
 {id:'sky',date:'21 Oct 2026',image:'sunset-clip',title:'No filter needed',views:'1,102',comments:[['maya','Pink sky club'],['priya','This is going in my moodboard'],['jordan','Looks like a loading screen']]},
 {id:'build',date:'18 Oct 2026',image:'roblox-avatar',title:'Outfit reveal ⚡ #Roblox',views:'3,214',comments:[['gamer','How many Robux did that cost'],['casey','All of them. Literally.'],['maya','Oops'],['jordan','See you on the Saturday stream'],['casey','Casey_Thunder on Twitch!'],['sportz','I love the blue']]},
 {id:'lights',date:'17 Oct 2026',image:'night-field',title:'Last one off the field',views:'2,761',comments:[['coach','Please remember your water bottles'],['casey','Mine was in my bag this time'],['maya','The sky 🧡']]}
];
ARTICLES['work-home'].image='studio-gallery';
ARTICLES['work-home'].title='Good design starts with listening.';
ARTICLES['work-home'].body=`<p class="studio-lead">We’re Cedar & Finch, an independent design studio in Lexington. We help people turn complicated ideas into identities, spaces, and websites that feel like them.</p><a class="studio-cta" href="#/article/designers">Meet our designers →</a><h2>Selected work</h2><div class="studio-grid"><a href="#/article/library-project"><h3>A new chapter</h3><p>Wayfinding & print · Neighborhood library</p></a><a href="#/article/garden-project"><h3>Room to grow</h3><p>Identity & digital · Community garden</p></a><a href="#/article/sponsor"><h3>Made for match day</h3><p>Event graphics · Riverdale Thunder</p></a></div><h2>A small studio. Many perspectives.</h2><p>We sketch around the same table, argue kindly about type, and make time to understand the people who will use what we create. Come explore our <a href="#/article/designers">team</a> and <a href="#/article/studio-journal">studio journal</a>.</p>`;
ARTICLES['dana-bio'].body=`<p class="studio-lead">Dana turns a pile of good ideas into a plan people can actually follow.</p><p>As project coordinator, she keeps schedules, print suppliers, and client conversations moving. She joined Cedar & Finch in 2022 after several years in Louisville, and still keeps a paper notebook beside her calendar.</p><p>“My favorite part is the moment someone sees their idea become a real thing. A sign, a booklet, a space—something they can point to and say, that’s ours.”</p><h2>Away from the studio</h2><p>Weekends tend to involve Casey’s soccer matches, Eli’s running commentary, and a library book Dana has promised herself she’ll finish. She volunteers with Riverdale Thunder and is the person most likely to bring far too many cupcakes. Her regular coffee order is an oat-milk latte; her studio mug has a chipped blue handle.</p><p>She collects old concert tickets, likes mystery novels, and believes a good project kickoff deserves actual conversation before anyone opens a spreadsheet.</p><p>Say hello: <strong>dana.selvin@cedarfinch.example</strong></p><p><a href="#/profile/dana">Dana’s Frame</a> · <a href="#/article/sponsor">Community Cup journal</a></p>`;
Object.assign(ARTICLES,{
 designers:{service:'work',title:'Different minds. Shared table.',date:'Meet our designers & project team',body:`<p class="studio-lead">The people who ask the extra question, notice the tiny detail, and stay curious.</p><div class="studio-grid"><a href="#/article/lena-bio"><h2>Lena Ortiz</h2><p>Brand & print designer</p><p>Type, texture, and the joy of making something by hand.</p></a><a href="#/article/dana-bio"><h2>Dana Selvin</h2><p>Project coordinator</p><p>A steady hand from the first conversation to the final delivery.</p></a><a href="#/article/sam-bio"><h2>Sam Reed</h2><p>Digital designer</p><p>Thoughtful websites for the people who use them.</p></a></div>`},
 'lena-bio':{service:'work',title:'Lena Ortiz',date:'Brand & print designer',body:`<p>Lena makes identities with a little personality and a lot of care. She grew up in Lexington and studied printmaking before joining the studio in 2021.</p><p>Outside work she teaches occasional lettering workshops at the arts center, hunts for old cookbooks, and posts her experiments as <a href="#/profile/lena">@lena.letters</a>.</p>`},
 'sam-bio':{service:'work',title:'Sam Reed',date:'Digital designer',body:`<p>Sam designs websites that work for busy people on ordinary devices. He joined Cedar & Finch in 2023 and keeps a shelf of board games by his desk.</p><p>Most Saturdays he volunteers at the community garden. His latest project is a seed-swap website. Find his notes on <a href="#/profile/sam">Frame</a>.</p>`},
 'studio-journal':{service:'work',title:'Notes from the studio',date:'Work, process & things we care about',body:`<h2><a href="#/article/sponsor">Made for match day</a></h2><p>Printed signs and a community effort at Riverdale Park.</p><h2><a href="#/article/library-project">A new chapter</a></h2><p>Helping visitors find their way.</p><h2><a href="#/article/garden-project">Room to grow</a></h2><p>A bright identity for a neighborhood project.</p>`},
 'library-project':{service:'work',title:'A new chapter',date:'Wayfinding · Print · 2026',image:'studio-gallery',body:`<p>The neighborhood library wanted its new readers’ room to feel welcoming before anyone reached the desk. Lena led the visual design; Dana coordinated the print schedule with library volunteer Ellis Morgan.</p><p>A flexible set of signs now connects books, events, and the people looking for them. The <a href="#/article/news-library">Lexington Ledger covered the reopening</a>.</p>`},
 'garden-project':{service:'work',title:'Room to grow',date:'Identity · Digital · 2026',image:'studio-desk',body:`<p>A shared garden needs more than a logo. Sam and Lena worked with volunteers on a seed-swap page, labels, and a simple noticeboard system.</p><p>The palette came from a box of seed packets. The type was chosen to be easy to read in bright sun. Sam still checks on the tomatoes every Saturday.</p>`},
 'news-cup':{service:'news',title:'Soccer, cupcakes, and a new set of goals',date:'24 October 2026 · Community · By Morgan Bell',image:'volunteers',body:`<p>Families filled Riverdale Park’s Field 3 on Saturday for the Thunder Community Cup, a fundraiser for youth team equipment. The event ran from 10 a.m. to 2 p.m., with matches, bake stalls, and plenty of sideline encouragement.</p><p>Volunteer coordinator Dana Selvin kept check-in moving with help from families and players. Casey Selvin, who wears number 7 for Riverdale Thunder, helped at the welcome table before joining her teammates.</p><p>Coach Kai Morgan praised the volunteers. “The kids remember the games, but it takes a lot of people to make a day like this happen.”</p><p>Cedar & Finch supplied the printed signs. Staff member Lena Ortiz said the wind provided an unexpected test of their mounting tape.</p><p>Priya Shah, a Riverdale yearbook photographer, captured the day alongside club photographers. More photos and the original event image are available in the <a href="#/article/recap">club’s photo recap</a>.</p><p>The organizers are wrapping up supply receipts this week; details are on the <a href="#/club">club website</a>.</p>`},
 'news-library':{service:'news',title:'Library readers’ room opens its doors',date:'22 October 2026 · Neighborhoods · By Morgan Bell',image:'studio-gallery',body:`<p>A brighter readers’ room welcomed visitors this week with new signs and a growing local-history shelf. Volunteer Ellis Morgan has been sorting donated photographs for a Sunday neighborhood walk.</p><p>The wayfinding was developed with <a href="#/work">Cedar & Finch</a>. Designer Lena Ortiz said the team tested the lettering from across the room before approving the final prints.</p><p>The history walk begins at the library steps Sunday at 10 a.m. Comfortable shoes are recommended.</p>`},
 'news-bikes':{service:'news',title:'A second life for well-loved bicycles',date:'24 October 2026 · Neighborhoods · By Jules Park',image:'corey-shop',body:`<p>At Spoke & Wrench, a neighborhood bicycle repair shop in Lexington, Corey Selvin spent Saturday morning working through squeaky brakes, punctured tires, and a stubborn bell on the library’s bike.</p><p>The workshop has bicycles on repair stands, a wall of hand tools, and racks of replacement tires. Selvin checks each repair before the bike leaves the shop.</p><p>“Sometimes a small adjustment makes a bike feel completely different,” he said. Between repairs, he shows customers how to check tire pressure and spot worn brake pads.</p><p>Find community updates on <a href="#/profile/corey">Corey’s public profile</a>.</p>`},
 'news-theatre':{service:'news',title:'Behind the curtain at Lafayette',date:'23 October 2026 · Arts · By Jules Park',body:`<p>Student stage crews are preparing for opening night next Friday. Casey Stevens, a senior, has spent the week painting scenery while the cast rehearses.</p><p>“The doors look real, but absolutely none of them open,” Stevens said. Lighting student Robin Hale says the final cues will be ready by Monday.</p><p>More backstage notes from <a href="#/profile/stevens">Casey Stevens</a>.</p>`},
 'news-market':{service:'news',title:'Autumn market makes room for local makers',date:'20 October 2026 · Arts · By Morgan Bell',body:`<p>Ceramicist June Ellis and woodworker Nolan Price will join more than twenty stallholders at next month’s autumn makers market.</p><p>Organizer Amira Cole is still looking for volunteers to help carry tables. Visitors can expect handmade bowls, paper goods, and a repair demonstration. The market is unrelated to this weekend’s soccer fundraiser.</p>`},
 'news-road':{service:'news',title:'Bridge resurfacing changes Monday bus route',date:'25 October 2026 · City desk · By Jules Park',body:`<p>Crews will resurface the pedestrian bridge beside Westbrook Green beginning Monday. The adjacent bus stop will move one block east for two days.</p><p>City spokesperson Ren Wallace said access to nearby businesses will remain open. Cyclists are asked to dismount on the temporary shared path.</p>`}
});
SEARCH_INDEX.splice(0,SEARCH_INDEX.length,
 {title:'Frame · photos and public profiles',route:'/social',site:'frame.training',text:'People, photos, and everyday moments. Search names and usernames on Frame.',keys:'casey selvin stevens corey dana maya jordan priya kai coach frame instagram people lexington'},
 {title:'Casey Selvin · Columbus',route:'/profile/other',site:'frame.training / casey_draws',text:'Sketchbooks, ceramics, and Columbus life.',keys:'casey selvin ohio columbus'},
 {title:'Casey Stevens · backstage notes',route:'/profile/stevens',site:'frame.training / casey.stevens',text:'Lafayette theatre crew, Lexington.',keys:'casey stevens lexington theatre'},
 {title:'Corey Selvin · cycling & repairs',route:'/profile/corey',site:'frame.training / corey.rides',text:'Bike repairs, weekend rides, and coffee in Lexington.',keys:'corey selvin lexington bike'},
 {title:'Casey Selvin · landscape architect',route:'/profile/denver',site:'frame.training / casey.trails',text:'Planting plans and trail notes from Denver.',keys:'casey selvin denver architecture'},
 {title:'Lexington Ledger',route:'/news',site:'ledger.training',text:'Local news, neighborhood stories, arts, and sport.',keys:'lexington ledger news community cup fundraiser riverdale casey selvin dana corey stevens library'},
 {title:'Cedar & Finch — Independent design studio',route:'/work',site:'cedarfinch.training',text:'Identities, spaces, and websites. Meet our Lexington team.',keys:'cedar finch dana selvin lena ortiz sam reed design work studio lexington'},
 {title:'Riverdale Thunder',route:'/club',site:'thunder.training',text:'Youth soccer, club news, and event information.',keys:'riverdale thunder community cup soccer fundraiser coach kai morgan lexington'},
 {title:'TikTok · Casey_Thunder13',route:'/tiktok/casey',site:'tiktok.training / casey_thunder13',text:'Soccer, little moments, and game clips.',keys:'caseythunder13 casey_thunder13 tiktok'},
 {title:'Twitch · Casey_Thunder',route:'/twitch/casey',site:'twitch.training / Casey_Thunder',text:'Public channel, games, and recent streams.',keys:'casey_thunder caseythunder twitch stream'},
 {title:'PlaySpace · player search',route:'/gaming',site:'playspace.training',text:'Find a player by username.',keys:'casey_thunder13 gaming roblox playspace'},
 {title:'2025 Thunder Community Cup',route:'/article/old',site:'thunder.training / archive / 2025',text:'Millcreek Park, Field B. October 2025 club archive.',keys:'thunder community cup millcreek fundraiser archive 2025'},
 {title:'Dana Selvin · Portland photography',route:'/article/dana-other',site:'directory.training',text:'Landscape photography in the Pacific Northwest.',keys:'dana selvin portland'}
);
// Keep the fictional websites conversational; investigation guidance belongs in the lab workspace.
ARTICLES['news-market'].body=ARTICLES['news-market'].body.replace(' The market is unrelated to this weekend’s soccer fundraiser.','');
ARTICLES.roster.body=`<p>Casey M. Selvin, 13, joined the Riverdale Thunder welcome session this week. The Riverdale Middle School student wears number 7 and helped new players settle into their first Lexington practice.</p><p>Her favorite part of the game? “When everyone gets involved.”</p><p>Photos from the session are on the <a href="#/profile/thunder">club’s Frame page</a>.</p>`;
ARTICLES.organizer.body=ARTICLES.organizer.body.replace(' This address is a fictional training address.','').replace('<p>Changes to this process will appear on this club page. A familiar name in an unexpected message is not sufficient confirmation.</p>','<p>Thank you for keeping the receipts organized. The club treasurer will close the event accounts after Monday’s deadline.</p>');
ARTICLES['casey-ohio'].body=ARTICLES['casey-ohio'].body.replace('<p>This summary may be incomplete. Verify identity using independent sources.</p>','');
PROFILES.maya.image='school-friends';PROFILES.maya.focus='10%';
PROFILES.jordan.image='school-friends';PROFILES.jordan.focus='95%';
// Search these profiles by a discovered handle, rather than handing them out for a real-name search.
for(const r of SEARCH_INDEX){if(r.route==='/tiktok/casey'||r.route==='/gaming')r.handles=['casey_thunder13'];if(r.route==='/twitch/casey')r.handles=['casey_thunder','caseythunder'];}

// Profile portraits and the same people in their everyday activities.
POSTS.s2={owner:'sam',date:'24 Oct 2026 · 09:15',images:['sam-garden'],text:'Saturday at the community garden. Checking the tomato starts before they move indoors for the cold weather. Nice to spend a morning away from a screen.',comments:[['lena','The tomatoes look happier than my desk plant.']]};
ARTICLES['casey-ohio'].image='casey-artist';
ARTICLES['dana-other'].image='sunset-clip';
ARTICLES['lena-bio'].image='lena-print';
ARTICLES['sam-bio'].image='sam-garden';
for(const [id,image,name] of [['lena-bio','lena-print','Lena Ortiz'],['dana-bio','dana-work','Dana Selvin'],['sam-bio','sam-garden','Sam Reed']]){
 ARTICLES.designers.body=ARTICLES.designers.body.replace(`<a href="#/article/${id}"><h2>`,`<a href="#/article/${id}"><img class="studio-person" src="assets/${image}.jpg" alt="${name}"><h2>`);
}

// Public figures and a busier local soccer community.
Object.assign(PROFILES,{
 rich:{name:'Rich Bay-B',handle:'richbayb',image:'rich-bay-b',bio:'Musician · diamond binkie arrives October 30 💎🍼 · Loud songs, tiny accessories.',stats:'8.2M followers · 312 following',featured:true,posts:['rb1']},
 goblina:{name:'Goblina Trollky',handle:'goblina.trollky',image:'goblina-premiere',bio:'Actress. Professional screamer. DEATH LEMON press tour 🍋🛸 · In theaters October 30.',stats:'3.7M followers · 486 following',featured:true,posts:['gt1']},
 animal:{name:'Mr. Animal',handle:'mr.animal',image:'mr-animal',bio:'Big challenges. Questionable ideas. Animal Bucks enthusiast. 🐾',stats:'42.8M followers · 102 following',featured:true,posts:['ma1']},
 zoe:{name:'Zoe Bennett',handle:'zoe.on.the.wing',image:'thunder-teammates',focus:'0%',bio:'Thunder #11 ⚽ · Riverdale MS · left wing, right playlist · sketchbook always in my bag',stats:'286 followers · 341 following',posts:['zo1','zo2']},
 mateo:{name:'Mateo Ruiz',handle:'mateo.saves',image:'thunder-teammates',focus:'50%',bio:'Riverdale Thunder keeper 🧤 #1 · Lexington · baking bread is harder than saving penalties',stats:'193 followers · 250 following',posts:['mt1']},
 harper:{name:'Harper Chen',handle:'harper.defends',image:'thunder-teammates',focus:'100%',bio:'Thunder #4 · defense & debate club · Lexington · borrowing everyone’s books',stats:'221 followers · 308 following',posts:['hc1']}
});
Object.assign(POSTS,{
 rb1:{owner:'rich',date:'25 Oct 2026 · 11:00',images:['rich-bay-b'],likes:'684,219',commentCount:28416,text:'DIAMOND BINKIE. October 30. Twelve tracks. Zero naps. 💎🍼 The studio said “make it mature” so I added a string section. Which track should get a video first?',comments:[['rich','Track 4 is called Nap Time Is Over. You have been warned.'],['casey','Zoe has played the teaser every single bus ride 😭'],['zoe','And I will do it again. Thunder warmup playlist needs this.'],['jordan','The pendant has a higher graphics budget than my entire setup'],['maya','Please tell me the vinyl is glittery'],['lena','The sleeve typography is doing a lot and I respect it.'],['gamer','String section went harder than expected']]},
 gt1:{owner:'goblina',date:'24 Oct 2026 · 15:40',images:['goblina-premiere'],likes:'312,870',commentCount:12603,text:'Day 6 of DEATH LEMON press. They asked how I prepared to fight an evil space lemon. I said I stopped buying lemonade. 🍋🛸 In theaters October 30. The universe is about to get bitter.',comments:[['goblina','The lemon has its own trailer. I do not want to talk about it.'],['harper','Debate topic: is the lemon technically an astronaut'],['maya','Making a tiny felt version immediately'],['casey','Maya please bring it to school'],['priya','The lighting on that poster is incredible'],['dana','This sounds like the kind of movie Eli would quote for a month.'],['stevens','Our theatre crew needs to study this prop department'],['sam','Finally a realistic depiction of my inbox']]},
 ma1:{owner:'animal',date:'23 Oct 2026 · 17:00',images:['mr-animal'],likes:'2,104,882',commentCount:94731,text:'NEW CHALLENGE: who can eat an ENTIRE BICYCLE first?! 🚲 Winner gets ONE MILLION ANIMAL BUCKS. The accountant has stopped answering my calls. The bicycle is refusing to comment.',comments:[['animal','Update from the prop department: the stunt bike is cake. The real one is going home with the crew.'],['corey','As a bicycle mechanic I have several questions.'],['jordan','What is the exchange rate between Animal Bucks and Robux'],['casey','Does the bell count as dessert'],['mateo','I made one loaf of bread and now you want a bicycle'],['ellis','Please return all library bicycles in one piece.'],['gamer','The accountant is the real main character'],['coach','I will stick to orange slices at halftime.']]},
 zo1:{owner:'zoe',date:'24 Oct 2026 · 17:25',images:['thunder-teammates'],text:'Wing, wall, keeper. Harper made about a thousand interceptions and Mateo saved the loudest penalty of the day. #11 signing off until I find my other glove.',comments:[['harper','Your glove is in my bag. Again.'],['mateo','I was mostly trying not to fall over'],['casey','The save was actually ridiculous'],['priya','Three people finally looking at the camera!']]},
 zo2:{owner:'zoe',date:'21 Oct 2026 · 18:30',images:['night-field'],text:'Last drill before the lights came on. Rich Bay-B teaser on repeat for the walk home. Diamond binkie cannot arrive soon enough.',comments:[['casey','We know every word and it is only fifteen seconds'],['harper','Some of us were trying to discuss books']]},
 mt1:{owner:'mateo',date:'22 Oct 2026 · 17:10',images:['thunder-teammates'],text:'Team photo outtake. Green shirt, loud gloves, quiet confidence. Harper says my keeper face looks like I forgot my homework. Bread update: still very flat.',comments:[['zoe','The bread could be a shin guard'],['coach','Good communication in the box today, Mateo.'],['casey','Bring the bread anyway']]},
 hc1:{owner:'harper',date:'20 Oct 2026 · 16:45',images:['thunder-teammates'],text:'Number 4, right side of the photo, left side of the defense. Practice then debate club prep. Currently arguing that the best movie villain could be a lemon.',comments:[['mateo','Your closing argument had better include zest'],['maya','Death Lemon opening weekend?'],['harper','Obviously.']]},
 th3:{owner:'thunder',date:'25 Oct 2026 · 10:20',images:['thunder-teammates'],text:'Sunday shout-outs: Zoe Bennett kept the wing moving, Mateo Ruiz stood tall in goal, and Harper Chen read every pass. Casey Selvin helped the new players settle in. Proud of this whole squad.',comments:[['zoe','Best team 💙'],['mateo','Thanks to everyone behind the goal cheering'],['harper','And thanks to whoever found my book'],['casey','It was under the cones 😂'],['coach','Every position matters. Excellent work.']]},
 th4:{owner:'thunder',date:'21 Oct 2026 · 18:45',images:['night-field'],text:'Midweek training: passing triangles, keeper reactions, and a very competitive crossbar challenge. Harper won. Nobody is allowed to pretend they let her win.',comments:[['harper','Thank you for putting that in writing'],['zoe','Rematch'],['mateo','My crossbar and I need a break']]},
 th5:{owner:'thunder',date:'18 Oct 2026 · 12:00',images:['field'],text:'Boot swap this Sunday: bring clean boots you have outgrown and see what fits. The clubhouse shelf also has two abandoned water bottles and one mystery scarf.',comments:[['dana','I will bring Casey’s old pair.'],['zoe','The scarf might be mine'],['ellis','Lovely way to keep good equipment in use.']]}
});
PROFILES.thunder.posts=['th3','p301','th4','th5','p302'];
POSTS.p101.comments.push(['zoe','Still singing on the bus home'],['harper','I found the missing cones'],['mateo','Next year I am joining cupcake quality control']);
ARTICLES['club-home'].body=`<p>Saturday matches, muddy boots, and a place for every player. We are Riverdale Thunder, a youth soccer club in Lexington.</p><h2>This week at Thunder</h2><ul><li><a href="#/article/thunder-weekly">From the touchline: saves, passing drills & a crossbar champion</a> — 25 October</li><li><a href="#/article/recap">Community Cup: thank you, Lexington</a> — 24 October</li><li><a href="#/article/organizer">Volunteer follow-up and receipt deadline</a> — 25 October</li><li><a href="#/article/current">2026 Community Cup announcement</a> — 12 October</li></ul><h2>Meet a few of the squad</h2><div class="squad-grid">${['zoe','mateo','harper','casey'].map(id=>`<a href="#/profile/${id}">${id==='casey'?`<img src="assets/casey.jpg" alt="Casey Selvin">`:`<span class="squad-face team-avatar" role="img" aria-label="${PROFILES[id].name}" style="--face-x:${id==='zoe'?'28%':id==='mateo'?'50%':'77%'}"></span>`}<strong>${PROFILES[id].name}</strong><span>@${PROFILES[id].handle}</span></a>`).join('')}</div><h2>Around the clubhouse</h2><p>Boot swap on Sunday. Bring clean boots you have outgrown. Ask Coach K about joining a practice session, or catch up with the team on <a href="#/profile/thunder">Frame @riverdale_thunder</a>.</p>`;
ARTICLES['thunder-weekly']={service:'club',title:'From the touchline',date:'25 October 2026 · Club journal',image:'thunder-teammates',body:`<p>It has been a busy week for the Thunder. Zoe Bennett (#11) kept the passing drills moving, Harper Chen (#4) won Wednesday’s crossbar challenge, and goalkeeper Mateo Ruiz (#1) earned the loudest cheer at the Community Cup.</p><p>“The best part was hearing everyone behind the goal,” Mateo said. Coach K praised the team’s communication and Casey Selvin’s help welcoming newer players.</p><h2>Small victories</h2><p>Every water bottle made it home on Wednesday. Almost every cone did. Harper’s missing library book turned up under the equipment bag.</p><h2>Boots with another season in them</h2><p>The Sunday boot swap returns this week. Families can leave clean, outgrown pairs on the clubhouse shelf. Any remaining boots will be offered at the next welcome session.</p><p>More photos and player updates on <a href="#/profile/thunder">the club’s Frame page</a>.</p>`};
ARTICLES.roster.body+=`<h2>More from the squad</h2><p><a href="#/profile/zoe">Zoe Bennett · #11</a> brings pace on the wing. <a href="#/profile/mateo">Mateo Ruiz · #1</a> keeps everyone talking in goal. <a href="#/profile/harper">Harper Chen · #4</a> reads the game from the back line.</p>`;
SEARCH_INDEX.push({title:'From the touchline · Riverdale Thunder',route:'/article/thunder-weekly',site:'thunder.training / journal',text:'This week’s soccer highlights, player news, and the Sunday boot swap.',keys:'riverdale thunder soccer zoe bennett mateo ruiz harper chen'});
for(const id of ['rich','goblina','animal','zoe','mateo','harper']){const p=PROFILES[id];SEARCH_INDEX.push({title:p.name+' · Frame',route:'/profile/'+id,site:'frame.training / '+p.handle,text:p.bio,keys:p.name+' '+p.handle+' '+p.bio});}

// Professional profiles connect the studio to the wider community.
ARTICLES['work-home'].body+='<p><a href="../linkedup/#/company/cedar">Cedar &amp; Finch on LinkedUP ↗</a></p>';
for(const id of ['dana','lena','sam'])ARTICLES[id+'-bio'].body+=`<p><a href="../linkedup/#/person/${id}">Professional profile on LinkedUP ↗</a></p>`;
SEARCH_INDEX.push({title:'LinkedUP · Professional community',route:'/article/linkedup',site:'linkedup.training',text:'Professional profiles, company news, and conversations from the Lexington community.',keys:'linkedup cedar finch professional dana selvin lena ortiz sam reed'});
ARTICLES.linkedup={service:'directory',title:'LinkedUP',date:'Professional community',body:'<p>Explore professional profiles, company updates, and conversations.</p><p><a href="../linkedup/">Open LinkedUP ↗</a></p>'};

POSTS.p301.comments.push(
 ['thunder','@casey_thunder13, what email should we use for your volunteer-hours confirmation? We are logging the check-in shifts tonight.'],
 ['casey','casey.selvin13@mail.example please! I helped set up the table before check-in too.'],
 ['thunder','Got it, thank you! We have the setup time on the sheet as well.']
);
